# Generated by Django 2.2.4 on 2019-08-27 08:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32751)),
            ],
        ),
    ]
