# Generated by Django 2.2.3 on 2019-07-25 07:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


def edit_initial_wagtail_data(apps, schema_editor):
    ContentType = apps.get_model('contenttypes.ContentType')
    HomePage = apps.get_model('IRMIS_wagtail.HomePage')
    Page = apps.get_model('wagtailcore.Page')
    Site = apps.get_model('wagtailcore.Site')
    # home page content type
    homepage_content_type, created = ContentType.objects.get_or_create(
        model='homepage',
        app_label='IRMIS_wagtail'
    )

    # Delete old home page
    old_home_page = Page.objects.get(path='00010001')
    old_home_page.path = 'temp'
    old_home_page.save()

    # Create homepage
    new_homepage = HomePage.objects.create(
        title="Welcome to IRMIS",
        slug='home',
        content_type=homepage_content_type,
        path='00010001',
        depth=2,
        numchild=0,
        url_path='/home/',
    )

    # Update default site
    default_site = Site.objects.get(is_default_site=True)
    default_site.root_page_id = new_homepage.id
    default_site.save()

    old_home_page.delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RunPython(edit_initial_wagtail_data),
    ]
