# Generated by Django 2.2.3 on 2019-07-25 11:21

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("IRMIS_wagtail", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body_en",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="body_pt",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="body_tet",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
