# Generated by Django 2.2.4 on 2020-01-21 03:00

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CsvDataSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=24)),
                (
                    "path",
                    models.TextField(
                        help_text="The path inside the git@github.com:catalpainternational/estrada-data-sources.git repository"
                    ),
                ),
                ("added", models.DateTimeField(auto_now=True)),
                (
                    "columns",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        help_text="The column names present in the csv",
                        size=None,
                    ),
                ),
            ],
            options={"unique_together": {("data_type", "path")},},
        ),
        migrations.CreateModel(
            name="CsvData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_index",
                    models.PositiveSmallIntegerField(
                        help_text="The row index from the source csv file"
                    ),
                ),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="csv_data_sources.CsvDataSource",
                    ),
                ),
            ],
        ),
    ]
