# Generated by Django 2.2.4 on 2020-03-13 05:18

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("csv_data_sources", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="csvdata",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data"], name="csv_data_so_data_be3a05_gin"
            ),
        ),
    ]
