# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.contrib.gis.db import models


class SourceRrmpis2014(models.Model):
    gid = models.AutoField(primary_key=True)
    rd_id = models.CharField(max_length=254, blank=True, null=True)
    cha_st = models.FloatField(blank=True, null=True)
    cha_end = models.FloatField(blank=True, null=True)
    rdcode_cn = models.CharField(max_length=20, blank=True, null=True)
    access_li = models.CharField(max_length=254, blank=True, null=True)
    surface = models.CharField(max_length=254, blank=True, null=True)
    population = models.FloatField(blank=True, null=True)
    comments = models.CharField(max_length=254, blank=True, null=True)
    rdcode02 = models.CharField(max_length=254, blank=True, null=True)
    cway_w_1 = models.FloatField(blank=True, null=True)
    totwidth_1 = models.FloatField(blank=True, null=True)
    max_rd_g_1 = models.FloatField(blank=True, null=True)
    workcode = models.CharField(max_length=254, blank=True, null=True)
    costperkm = models.FloatField(blank=True, null=True)
    cost = models.FloatField(blank=True, null=True)
    sched = models.CharField(max_length=20, blank=True, null=True)
    lenkm = models.FloatField(blank=True, null=True)
    maxgraddeg = models.FloatField(blank=True, null=True)
    maxgradper = models.FloatField(blank=True, null=True)
    sbgrade = models.CharField(max_length=254, blank=True, null=True)
    pvment_typ = models.CharField(max_length=254, blank=True, null=True)
    paved_type = models.FloatField(blank=True, null=True)
    pvment_con = models.CharField(max_length=254, blank=True, null=True)
    cway_w = models.FloatField(blank=True, null=True)
    totwidth = models.FloatField(blank=True, null=True)
    sldr_cond = models.CharField(max_length=254, blank=True, null=True)
    side_drain = models.CharField(max_length=254, blank=True, null=True)
    sdrn_cond = models.CharField(max_length=254, blank=True, null=True)
    access_l_1 = models.CharField(max_length=254, blank=True, null=True)
    max_rd_grd = models.FloatField(blank=True, null=True)
    side_slope = models.FloatField(blank=True, null=True)
    rw_above = models.CharField(max_length=254, blank=True, null=True)
    rw_below = models.FloatField(blank=True, null=True)
    linm_above = models.FloatField(blank=True, null=True)
    linm_below = models.FloatField(blank=True, null=True)
    link_ref = models.CharField(max_length=254, blank=True, null=True)
    chainge_fr = models.FloatField(blank=True, null=True)
    chainge_to = models.FloatField(blank=True, null=True)
    sheet_ref = models.CharField(max_length=254, blank=True, null=True)
    surveyor = models.CharField(max_length=254, blank=True, null=True)
    surv_date = models.DateField(blank=True, null=True)
    sketch_map = models.CharField(max_length=254, blank=True, null=True)
    loctn_narr = models.FloatField(blank=True, null=True)
    date_const = models.FloatField(blank=True, null=True)
    typ_subgrd = models.CharField(max_length=254, blank=True, null=True)
    curr_pvmnt = models.CharField(max_length=254, blank=True, null=True)
    orig_pvmnt = models.CharField(max_length=254, blank=True, null=True)
    curr_drnge = models.CharField(max_length=254, blank=True, null=True)
    tech_commt = models.FloatField(blank=True, null=True)
    terr_class = models.CharField(max_length=254, blank=True, null=True)
    terr_commt = models.FloatField(blank=True, null=True)
    reason_4tr = models.CharField(max_length=254, blank=True, null=True)
    facilities = models.CharField(max_length=254, blank=True, null=True)
    goods = models.CharField(max_length=254, blank=True, null=True)
    fnct_class = models.CharField(max_length=254, blank=True, null=True)
    pub_transp = models.CharField(max_length=254, blank=True, null=True)
    fnct_commt = models.CharField(max_length=254, blank=True, null=True)
    peak_jan = models.CharField(max_length=254, blank=True, null=True)
    peak_feb = models.CharField(max_length=254, blank=True, null=True)
    peak_mar = models.CharField(max_length=254, blank=True, null=True)
    peak_apr = models.CharField(max_length=254, blank=True, null=True)
    peak_may = models.CharField(max_length=254, blank=True, null=True)
    peak_jun = models.CharField(max_length=254, blank=True, null=True)
    peak_jul = models.CharField(max_length=254, blank=True, null=True)
    peak_aug = models.CharField(max_length=254, blank=True, null=True)
    peak_sep = models.CharField(max_length=254, blank=True, null=True)
    peak_oct = models.CharField(max_length=254, blank=True, null=True)
    peak_nov = models.CharField(max_length=254, blank=True, null=True)
    peak_dec = models.CharField(max_length=254, blank=True, null=True)
    peak_sun = models.CharField(max_length=254, blank=True, null=True)
    peak_mon = models.CharField(max_length=254, blank=True, null=True)
    peak_tue = models.CharField(max_length=254, blank=True, null=True)
    peak_wed = models.CharField(max_length=254, blank=True, null=True)
    peak_thu = models.CharField(max_length=254, blank=True, null=True)
    peak_fri = models.CharField(max_length=254, blank=True, null=True)
    peak_sat = models.CharField(max_length=254, blank=True, null=True)
    tr_est_ang = models.FloatField(blank=True, null=True)
    tr_est_tru = models.FloatField(blank=True, null=True)
    tr_est_bus = models.FloatField(blank=True, null=True)
    tr_est_mic = models.FloatField(blank=True, null=True)
    tr_est_4wd = models.FloatField(blank=True, null=True)
    tr_est_2wd = models.FloatField(blank=True, null=True)
    tr_est_hor = models.FloatField(blank=True, null=True)
    tr_est_mot = models.FloatField(blank=True, null=True)
    tr_est_bic = models.FloatField(blank=True, null=True)
    tr_est_ped = models.FloatField(blank=True, null=True)
    sa_st_comm = models.CharField(max_length=254, blank=True, null=True)
    sand_km = models.FloatField(blank=True, null=True)
    sand_price = models.FloatField(blank=True, null=True)
    ston_km = models.FloatField(blank=True, null=True)
    ston_price = models.FloatField(blank=True, null=True)
    aggr_commt = models.FloatField(blank=True, null=True)
    aggr_km = models.FloatField(blank=True, null=True)
    aggr_price = models.FloatField(blank=True, null=True)
    watr_commt = models.FloatField(blank=True, null=True)
    watr_km = models.FloatField(blank=True, null=True)
    watr_price = models.FloatField(blank=True, null=True)
    cmnt_commt = models.CharField(max_length=254, blank=True, null=True)
    cmnt_km = models.FloatField(blank=True, null=True)
    cmnt_price = models.FloatField(blank=True, null=True)
    othr_commt = models.FloatField(blank=True, null=True)
    audio_impt = models.CharField(max_length=254, blank=True, null=True)
    audio_comm = models.FloatField(blank=True, null=True)
    time_start = models.FloatField(blank=True, null=True)
    time_end = models.FloatField(blank=True, null=True)
    weath_code = models.CharField(max_length=254, blank=True, null=True)
    weath_comm = models.CharField(max_length=254, blank=True, null=True)
    wp_start = models.FloatField(blank=True, null=True)
    wp_lat = models.FloatField(blank=True, null=True)
    wp_long = models.FloatField(blank=True, null=True)
    tr_obs_ang = models.FloatField(blank=True, null=True)
    tr_obs_tru = models.FloatField(blank=True, null=True)
    tr_obs_bus = models.FloatField(blank=True, null=True)
    tr_obs_mic = models.FloatField(blank=True, null=True)
    tr_obs_4wd = models.FloatField(blank=True, null=True)
    tr_obs_2wd = models.FloatField(blank=True, null=True)
    tr_obs_hor = models.FloatField(blank=True, null=True)
    tr_obs_mot = models.FloatField(blank=True, null=True)
    tr_obs_bic = models.FloatField(blank=True, null=True)
    tr_obs_ped = models.FloatField(blank=True, null=True)
    key_wp = models.FloatField(blank=True, null=True)
    key_extent = models.FloatField(blank=True, null=True)
    key_nature = models.CharField(max_length=254, blank=True, null=True)
    key_chn_fr = models.CharField(max_length=254, blank=True, null=True)
    key_chn_to = models.FloatField(blank=True, null=True)
    key_commnt = models.CharField(max_length=254, blank=True, null=True)
    note = models.CharField(max_length=10, blank=True, null=True)
    suconame = models.CharField(max_length=20, blank=True, null=True)
    subdstcode = models.SmallIntegerField(blank=True, null=True)
    distcode = models.SmallIntegerField(blank=True, null=True)
    distname = models.CharField(max_length=15, blank=True, null=True)
    subdistrct = models.CharField(max_length=20, blank=True, null=True)
    sucocode = models.IntegerField(blank=True, null=True)
    rdidfin = models.CharField(max_length=10, blank=True, null=True)
    geom = models.MultiLineStringField(srid=32751, dim=4, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "source_rrmpis_2014"
