// source: survey.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.assets.Report', null, global);
goog.exportSymbol('proto.assets.Survey', null, global);
goog.exportSymbol('proto.assets.Surveys', null, global);
goog.exportSymbol('proto.assets.TableEntry', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.assets.Survey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.assets.Survey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.assets.Survey.displayName = 'proto.assets.Survey';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.assets.Surveys = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.assets.Surveys.repeatedFields_, null);
};
goog.inherits(proto.assets.Surveys, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.assets.Surveys.displayName = 'proto.assets.Surveys';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.assets.Report = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.assets.Report.repeatedFields_, null);
};
goog.inherits(proto.assets.Report, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.assets.Report.displayName = 'proto.assets.Report';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.assets.TableEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.assets.TableEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.assets.TableEntry.displayName = 'proto.assets.TableEntry';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.assets.Survey.prototype.toObject = function(opt_includeInstance) {
  return proto.assets.Survey.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.assets.Survey} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assets.Survey.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    road: jspb.Message.getFieldWithDefault(msg, 2, ""),
    user: jspb.Message.getFieldWithDefault(msg, 3, 0),
    source: jspb.Message.getFieldWithDefault(msg, 9, ""),
    dateUpdated: (f = msg.getDateUpdated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    dateSurveyed: (f = msg.getDateSurveyed()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    chainageStart: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    chainageEnd: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    values: jspb.Message.getFieldWithDefault(msg, 7, ""),
    addedBy: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.assets.Survey}
 */
proto.assets.Survey.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.assets.Survey;
  return proto.assets.Survey.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.assets.Survey} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.assets.Survey}
 */
proto.assets.Survey.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoad(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setUser(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setSource(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDateUpdated(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDateSurveyed(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setChainageStart(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setChainageEnd(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setValues(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddedBy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.assets.Survey.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.assets.Survey.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.assets.Survey} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assets.Survey.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getRoad();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUser();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getSource();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getDateUpdated();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDateSurveyed();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getChainageStart();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getChainageEnd();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getValues();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getAddedBy();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional uint32 id = 1;
 * @return {number}
 */
proto.assets.Survey.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.assets.Survey.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string road = 2;
 * @return {string}
 */
proto.assets.Survey.prototype.getRoad = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.assets.Survey.prototype.setRoad = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 user = 3;
 * @return {number}
 */
proto.assets.Survey.prototype.getUser = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.assets.Survey.prototype.setUser = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string source = 9;
 * @return {string}
 */
proto.assets.Survey.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.assets.Survey.prototype.setSource = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional google.protobuf.Timestamp date_updated = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.assets.Survey.prototype.getDateUpdated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.assets.Survey.prototype.setDateUpdated = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.assets.Survey.prototype.clearDateUpdated = function() {
  this.setDateUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.assets.Survey.prototype.hasDateUpdated = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Timestamp date_surveyed = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.assets.Survey.prototype.getDateSurveyed = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.assets.Survey.prototype.setDateSurveyed = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.assets.Survey.prototype.clearDateSurveyed = function() {
  this.setDateSurveyed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.assets.Survey.prototype.hasDateSurveyed = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional float chainage_start = 5;
 * @return {number}
 */
proto.assets.Survey.prototype.getChainageStart = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.assets.Survey.prototype.setChainageStart = function(value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional float chainage_end = 6;
 * @return {number}
 */
proto.assets.Survey.prototype.getChainageEnd = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/** @param {number} value */
proto.assets.Survey.prototype.setChainageEnd = function(value) {
  jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional string values = 7;
 * @return {string}
 */
proto.assets.Survey.prototype.getValues = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.assets.Survey.prototype.setValues = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string added_by = 11;
 * @return {string}
 */
proto.assets.Survey.prototype.getAddedBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/** @param {string} value */
proto.assets.Survey.prototype.setAddedBy = function(value) {
  jspb.Message.setProto3StringField(this, 11, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.assets.Surveys.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.assets.Surveys.prototype.toObject = function(opt_includeInstance) {
  return proto.assets.Surveys.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.assets.Surveys} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assets.Surveys.toObject = function(includeInstance, msg) {
  var f, obj = {
    surveysList: jspb.Message.toObjectList(msg.getSurveysList(),
    proto.assets.Survey.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.assets.Surveys}
 */
proto.assets.Surveys.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.assets.Surveys;
  return proto.assets.Surveys.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.assets.Surveys} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.assets.Surveys}
 */
proto.assets.Surveys.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.assets.Survey;
      reader.readMessage(value,proto.assets.Survey.deserializeBinaryFromReader);
      msg.addSurveys(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.assets.Surveys.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.assets.Surveys.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.assets.Surveys} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assets.Surveys.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSurveysList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.assets.Survey.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Survey surveys = 1;
 * @return {!Array<!proto.assets.Survey>}
 */
proto.assets.Surveys.prototype.getSurveysList = function() {
  return /** @type{!Array<!proto.assets.Survey>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.assets.Survey, 1));
};


/** @param {!Array<!proto.assets.Survey>} value */
proto.assets.Surveys.prototype.setSurveysList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.assets.Survey=} opt_value
 * @param {number=} opt_index
 * @return {!proto.assets.Survey}
 */
proto.assets.Surveys.prototype.addSurveys = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.assets.Survey, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.assets.Surveys.prototype.clearSurveysList = function() {
  this.setSurveysList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.assets.Report.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.assets.Report.prototype.toObject = function(opt_includeInstance) {
  return proto.assets.Report.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.assets.Report} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assets.Report.toObject = function(includeInstance, msg) {
  var f, obj = {
    roadCode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    reportChainageStart: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    reportChainageEnd: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    counts: jspb.Message.getFieldWithDefault(msg, 4, ""),
    percentages: jspb.Message.getFieldWithDefault(msg, 5, ""),
    tableList: jspb.Message.toObjectList(msg.getTableList(),
    proto.assets.TableEntry.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.assets.Report}
 */
proto.assets.Report.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.assets.Report;
  return proto.assets.Report.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.assets.Report} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.assets.Report}
 */
proto.assets.Report.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoadCode(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setReportChainageStart(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setReportChainageEnd(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCounts(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPercentages(value);
      break;
    case 6:
      var value = new proto.assets.TableEntry;
      reader.readMessage(value,proto.assets.TableEntry.deserializeBinaryFromReader);
      msg.addTable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.assets.Report.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.assets.Report.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.assets.Report} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assets.Report.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRoadCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReportChainageStart();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getReportChainageEnd();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getCounts();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPercentages();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTableList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.assets.TableEntry.serializeBinaryToWriter
    );
  }
};


/**
 * optional string road_code = 1;
 * @return {string}
 */
proto.assets.Report.prototype.getRoadCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.assets.Report.prototype.setRoadCode = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float report_chainage_start = 2;
 * @return {number}
 */
proto.assets.Report.prototype.getReportChainageStart = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.assets.Report.prototype.setReportChainageStart = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float report_chainage_end = 3;
 * @return {number}
 */
proto.assets.Report.prototype.getReportChainageEnd = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.assets.Report.prototype.setReportChainageEnd = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional string counts = 4;
 * @return {string}
 */
proto.assets.Report.prototype.getCounts = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.assets.Report.prototype.setCounts = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string percentages = 5;
 * @return {string}
 */
proto.assets.Report.prototype.getPercentages = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.assets.Report.prototype.setPercentages = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated TableEntry table = 6;
 * @return {!Array<!proto.assets.TableEntry>}
 */
proto.assets.Report.prototype.getTableList = function() {
  return /** @type{!Array<!proto.assets.TableEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.assets.TableEntry, 6));
};


/** @param {!Array<!proto.assets.TableEntry>} value */
proto.assets.Report.prototype.setTableList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.assets.TableEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.assets.TableEntry}
 */
proto.assets.Report.prototype.addTable = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.assets.TableEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.assets.Report.prototype.clearTableList = function() {
  this.setTableList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.assets.TableEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.assets.TableEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.assets.TableEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assets.TableEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    chainageStart: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    chainageEnd: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    surfaceCondition: jspb.Message.getFieldWithDefault(msg, 3, ""),
    surveyId: jspb.Message.getFieldWithDefault(msg, 4, 0),
    dateSurveyed: (f = msg.getDateSurveyed()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    addedBy: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.assets.TableEntry}
 */
proto.assets.TableEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.assets.TableEntry;
  return proto.assets.TableEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.assets.TableEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.assets.TableEntry}
 */
proto.assets.TableEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setChainageStart(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setChainageEnd(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSurfaceCondition(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSurveyId(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDateSurveyed(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddedBy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.assets.TableEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.assets.TableEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.assets.TableEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assets.TableEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChainageStart();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getChainageEnd();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getSurfaceCondition();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSurveyId();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getDateSurveyed();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getAddedBy();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional float chainage_start = 1;
 * @return {number}
 */
proto.assets.TableEntry.prototype.getChainageStart = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/** @param {number} value */
proto.assets.TableEntry.prototype.setChainageStart = function(value) {
  jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional float chainage_end = 2;
 * @return {number}
 */
proto.assets.TableEntry.prototype.getChainageEnd = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.assets.TableEntry.prototype.setChainageEnd = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional string surface_condition = 3;
 * @return {string}
 */
proto.assets.TableEntry.prototype.getSurfaceCondition = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.assets.TableEntry.prototype.setSurfaceCondition = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 survey_id = 4;
 * @return {number}
 */
proto.assets.TableEntry.prototype.getSurveyId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.assets.TableEntry.prototype.setSurveyId = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp date_surveyed = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.assets.TableEntry.prototype.getDateSurveyed = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.assets.TableEntry.prototype.setDateSurveyed = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.assets.TableEntry.prototype.clearDateSurveyed = function() {
  this.setDateSurveyed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.assets.TableEntry.prototype.hasDateSurveyed = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string added_by = 6;
 * @return {string}
 */
proto.assets.TableEntry.prototype.getAddedBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.assets.TableEntry.prototype.setAddedBy = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.assets);
