/* global gettext */
/* This file is an autogenerated collation of gettext calls in other files */
/* Allowing django makemessages to pick up gettext calls in riot markup */
gettext('E.g. A01-01');
gettext('E.g. Dili');
gettext('E.g. Manatuto');
gettext('E.g. 58.7');
gettext('E.g. 5.0');
gettext('E.g. 0+000');
gettext('E.g. 62+410');
gettext('Close');
gettext('Success');
gettext('You have successfully saved');
gettext('Error');
gettext('Something went wrong');
