/* global gettext */
/* This file is an autogenerated collation of gettext calls in other files */
/* Allowing django makemessages to pick up gettext calls in riot markup */
gettext('Asset');
gettext('Link code and name');
gettext('Link Code');
gettext('E.g. A01-01');
gettext('Enter link code according to DRBFC standard');
gettext('Link Start Name');
gettext('E.g. Dili');
gettext('Enter the name of the link start location (municipal center, administrative post or nearest suco)');
gettext('Link End Name');
gettext('E.g. Manatuto');
gettext('Enter the name of the link end location (municipal center, administrative post or nearest suco)');
gettext('Link width and length');
gettext('Link Length');
gettext('E.g. 58.7');
gettext('Enter road link length (in Km)');
gettext('Carriageway Width');
gettext('E.g. 5.0');
gettext('Enter the width (in meters) of the link carriageway');
gettext('Link chainage');
gettext('Link Start Chainage');
gettext('E.g. 0+000');
gettext('Enter chainage for link starting point');
gettext('Link End Chainage');
gettext('E.g. 62+410');
gettext('Enter chainage for link ending point');
gettext('Save and continue');
gettext('Edit asset');
gettext('Location & Type');
gettext('Asset Details');
gettext('Pavement');
gettext('Project');
gettext('Condition');
