-- Important Pre-requisites

-- Go to assets/roadstatus and add the road status
-- code='n', name='Planned', name[en]='Planned'
-- * this MUST end up with an id of 4
-- Alternatively use the following INSERT statement and check the results with the SELECT
INSERT INTO assets_roadStatus (id, code, name, name_tet, name_pt, name_en ) VALUES (4, 'n', 'Planned', DEFAULT, DEFAULT, 'Planned' );
SELECT * FROM assets_roadStatus;

-- Go to assets/surfacetype and add in the surface type
-- code=9 (or '9'), name='Bitumen', name[en]='Bitumen'
-- * this MUST end up with an id of 9
-- Note that this surface type is recorded as 'BT' in the Excel file
-- Alternatively use the following INSERT statement and check the results with the SELECT
INSERT INTO assets_surfaceType (id, code, name, name_tet, name_pt, name_en ) VALUES (9, 9, 'Bitumen', DEFAULT, DEFAULT, 'Bitumen' );
SELECT * FROM assets_surfaceType;

UPDATE assets_road SET road_code='A01', road_name='Dili - Com',link_code='A01-01', link_start_name='Dili (Junction A3A2)', link_end_name='Manatuto (Juction A09)',carriageway_width=5.000,funding_source='JICA', project='DBHP 2016-2022',surface_type_id=9,pavement_class_id=1,road_status_id=2,technical_class_id=6,traffic_level='H',surface_condition='1',administrative_area='Dili' WHERE id=1;
UPDATE assets_road SET road_code='A01', road_name='Dili - Com',link_code='A01-02', link_start_name='Manatuto (Junction A09)', link_end_name='Baucau (Junction A06)',carriageway_width=5.000,funding_source='ADB', project='DBHP 2016-2022',surface_type_id=9,pavement_class_id=1,road_status_id=2,technical_class_id=6,traffic_level='M',surface_condition='1',administrative_area='Manatuto' WHERE id=2;
UPDATE assets_road SET road_code='A01', road_name='Dili - Com',link_code='A01-03', link_start_name='Baucau (Junction A06)', link_end_name='Lautem (Junction A08)',carriageway_width=4.300,funding_source='ADB', project='RNUSP 2014-2020',surface_type_id=9,pavement_class_id=1,road_status_id=2,technical_class_id=6,traffic_level='M',surface_condition='2',administrative_area='Baucau' WHERE id=5;
UPDATE assets_road SET road_code='A01', road_name='Dili - Com',link_code='A01-04', link_start_name='Lautem (Junction A08)', link_end_name='Com',carriageway_width=4.500,funding_source='-',surface_type_id=9,pavement_class_id=1,road_status_id=4,technical_class_id=6,traffic_level='L',surface_condition='1',administrative_area='Lautem' WHERE id=22;
UPDATE assets_road SET road_code='A02', road_name='Dili-Suai',link_code='A02-01', link_start_name='Dili (Junction A3A1)', link_end_name='Aileu',carriageway_width=5.000,funding_source='WB', project='RCRP 2012-2018',surface_type_id=9,pavement_class_id=1,road_status_id=1,technical_class_id=6,traffic_level='M',surface_condition='1',administrative_area='Dili' WHERE id=6;
UPDATE assets_road SET road_code='A02', road_name='Dili-Suai',link_code='A02-02', link_start_name='Aileu', link_end_name='Maubissi',carriageway_width=4.500,funding_source='WB', project='RCRP 2012-2018',surface_type_id=9,pavement_class_id=1,road_status_id=1,technical_class_id=6,traffic_level='M',surface_condition='1',administrative_area='Aileu' WHERE id=27;
UPDATE assets_road SET road_code='A02', road_name='Dili-Suai',link_code='A02-03', link_start_name='Maubissi', link_end_name='Aituto (Junction A5)',carriageway_width=4.500,funding_source='WB', project='RCRP 2012-2018',surface_type_id=9,pavement_class_id=1,road_status_id=1,technical_class_id=6,traffic_level='M',surface_condition='1',administrative_area='Maubissi' WHERE id=28;
UPDATE assets_road SET road_code='A02', road_name='Dili-Suai',link_code='A02-04', link_start_name='Aituto (Junction A5)', link_end_name='Ainaro',carriageway_width=4.300,funding_source='WB', project='RCRP 2012-2018',surface_type_id=9,pavement_class_id=1,road_status_id=1,technical_class_id=6,traffic_level='M',surface_condition='1',administrative_area='Aituto' WHERE id=7;
UPDATE assets_road SET road_code='A02', road_name='Dili-Suai',link_code='A02-05', link_start_name='Ainaro', link_end_name='Cassa (Junction A13)',carriageway_width=4.500,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='M',surface_condition='1',administrative_area='Ainaro' WHERE id=17;
UPDATE assets_road SET road_code='A02', road_name='Dili-Suai',link_code='A02-06', link_start_name='Cassa (Juction A13)', link_end_name='Zumalai (Junction A12)',carriageway_width=4.300,funding_source='TimorGap', project='TimorGap',surface_type_id=9,pavement_class_id=1,road_status_id=1,technical_class_id=6,traffic_level='M',surface_condition='3',administrative_area='Cassa' WHERE id=29;
UPDATE assets_road SET road_code='A02', road_name='Dili-Suai',link_code='A02-07', link_start_name='Zumalai (Junction A12)', link_end_name='Suai (Junction C21)',carriageway_width=4.300,funding_source='TimorGap', project='TimorGap',surface_type_id=9,pavement_class_id=1,road_status_id=1,technical_class_id=6,traffic_level='M',surface_condition='2',administrative_area='Zumalai' WHERE id=19;
UPDATE assets_road SET road_code='A03', road_name='Dili-Maliana',link_code='A03-01', link_start_name='Dili (Junction A2A1)', link_end_name='Tibar (Junction A4)',carriageway_width=5.800,funding_source='ADB', project='RNUP 2012-2017',surface_type_id=9,pavement_class_id=1,road_status_id=1,technical_class_id=6,traffic_level='H',surface_condition='1',administrative_area='Dili' WHERE id=30;
UPDATE assets_road SET road_code='A03', road_name='Dili-Maliana',link_code='A03-02', link_start_name='Tibar', link_end_name='Liquica (A03)',carriageway_width=4.300,funding_source='ADB', project='RNUP 2012-2017',surface_type_id=9,pavement_class_id=1,road_status_id=1,technical_class_id=6,traffic_level='H',surface_condition='1',administrative_area='Tibar' WHERE id=48;
UPDATE assets_road SET road_code='A03', road_name='Dili-Maliana',link_code='A03-03', link_start_name='Liquica', link_end_name='Batugade',carriageway_width=4.300,funding_source='ADB', project='RNDSP + RNUSP 2014-2020',surface_type_id=9,pavement_class_id=1,road_status_id=2,technical_class_id=6,traffic_level='H',surface_condition='1',administrative_area='Liquica' WHERE id=31;
UPDATE assets_road SET road_code='A03', road_name='Dili-Maliana',link_code='A03-04', link_start_name='Batugade', link_end_name='Mota Ain (Indonesia Border)',carriageway_width=4.500,funding_source='ADB', project='RNUSP 2014-2020',surface_type_id=9,pavement_class_id=1,road_status_id=2,technical_class_id=6,traffic_level='H',surface_condition='2',administrative_area='Batugade' WHERE id=47;
UPDATE assets_road SET road_code='A03', road_name='Dili-Maliana',link_code='A03-05', link_start_name='Batugade', link_end_name='Maliana (Junction A12)',carriageway_width=4.400,funding_source='-', project='RNDSP + RNUSP 2014-2020',surface_type_id=9,pavement_class_id=1,road_status_id=2,technical_class_id=6,traffic_level='M',surface_condition='2',administrative_area='Batugade' WHERE id=16;
UPDATE assets_road SET road_code='A04', road_name='Tibar-Ermera',link_code='A04-01', link_start_name='Tibar (Junction A3)', link_end_name='Gleno',carriageway_width=4.600,funding_source='ADB', project='RNUP 2012-2017',surface_type_id=9,pavement_class_id=1,road_status_id=1,technical_class_id=6,traffic_level='M',surface_condition='1',administrative_area='Tibar' WHERE id=9;
UPDATE assets_road SET road_code='A04', road_name='Tibar-Ermera',link_code='A04-02', link_start_name='Gleno', link_end_name='Ermera (Gleno Market - Junction C22)',carriageway_width=4.300,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='M',surface_condition='2',administrative_area='Gleno' WHERE id=46;
UPDATE assets_road SET road_code='A04', road_name='Tibar-Ermera',link_code='A04-03', link_start_name='Gleno', link_end_name='Ermera (Junction C22 - Junction A4/03)',funding_source='-',administrative_area='Gleno' WHERE id=44;
UPDATE assets_road SET road_code='A04', road_name='Tibar-Ermera',link_code='A04-04', link_start_name='Gleno', link_end_name='Ermera (Junction A11  - Ermera villa)',funding_source='-',administrative_area='Gleno' WHERE id=45;
UPDATE assets_road SET road_code='A05', road_name='Aituto-Betano',link_code='A05-01/A05-02', link_start_name='Aituto (Junction A2)', link_end_name='Same',carriageway_width=4.000,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='M',surface_condition='3',administrative_area='Aituto' WHERE id=8;
UPDATE assets_road SET road_code='A05', road_name='Aituto-Betano',link_code='A05-03', link_start_name='Same', link_end_name='Betano',funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,administrative_area='Same' WHERE id=12;
UPDATE assets_road SET road_code='A06', road_name='Baucau-Viqueque',link_code='A06-01', link_start_name='Baucau (Junction A2)', link_end_name='Venilale',carriageway_width=4.000,funding_source='ADB', project='BVHP 2018-2022',surface_type_id=9,pavement_class_id=1,road_status_id=2,technical_class_id=6,traffic_level='M',surface_condition='2',administrative_area='Baucau' WHERE id=32;
UPDATE assets_road SET road_code='A06', road_name='Baucau-Viqueque',link_code='A06-02', link_start_name='Venilale', link_end_name='Viqueque',carriageway_width=4.000,funding_source='ADB', project='BVHP 2018-2022',surface_type_id=9,pavement_class_id=1,road_status_id=2,technical_class_id=6,traffic_level='M',surface_condition='3',administrative_area='Venilale' WHERE id=3;
UPDATE assets_road SET road_code='A07', road_name='Viqueque-Natabora',link_code='A07-01', link_start_name='Viqueque (Junction A8)', link_end_name='Natarbora (Junction A9)',carriageway_width=3.200,funding_source='TimorGap', project='TimorGap',surface_type_id=9,pavement_class_id=1,road_status_id=4,technical_class_id=6,traffic_level='L',surface_condition='2',administrative_area='Viqueque' WHERE id=15;
UPDATE assets_road SET road_code='A08', road_name='Viqueque-Lautem',link_code='A08-01', link_start_name='Viqueque (Junction A6A7)', link_end_name='Uatocarbau (Junction C8)',carriageway_width=3.000,funding_source='TimorGap', project='TimorGap',surface_type_id=9,pavement_class_id=1,road_status_id=4,technical_class_id=6,traffic_level='M',surface_condition='4',administrative_area='Viqueque' WHERE id=33;
UPDATE assets_road SET road_code='A08', road_name='Viqueque-Lautem',link_code='A08-02', link_start_name='Uatocarbau', link_end_name='Iliomar (Juction C1)',carriageway_width=3.200,funding_source='-',surface_type_id=1,pavement_class_id=2,technical_class_id=6,traffic_level='L',surface_condition='4',administrative_area='Uatocarbau' WHERE id=34;
UPDATE assets_road SET road_code='A08', road_name='Viqueque-Lautem',link_code='A08-03', link_start_name='Iliomar (Junction C1)', link_end_name='Lospalos (Kota)',carriageway_width=3.200,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='L',surface_condition='4',administrative_area='Iliomar' WHERE id=4;
UPDATE assets_road SET road_code='A08', road_name='Viqueque-Lautem',link_code='A08-04', link_start_name='Lospalos (via Tarisula)', link_end_name='Lautem (Junction A1)',carriageway_width=4.000,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='M',surface_condition='2',administrative_area='Lospalos' WHERE id=21;
UPDATE assets_road SET road_code='A09', road_name='Manatuto-Natabora',link_code='A09-01', link_start_name='Manatuto (A1)', link_end_name='Cribas (Atahoc)',carriageway_width=4.600,funding_source='ADB', project='ADB RNSUP 2014-2020',surface_type_id=9,pavement_class_id=1,road_status_id=2,technical_class_id=6,traffic_level='L',surface_condition='3',administrative_area='Manatuto' WHERE id=35;
UPDATE assets_road SET road_code='A09', road_name='Manatuto-Natabora',link_code='A09-02', link_start_name='Cribas (Atahoc)', link_end_name='Laclubar (Junction C15)',carriageway_width=3.500,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='L',surface_condition='4',administrative_area='Cribas' WHERE id=36;
UPDATE assets_road SET road_code='A09', road_name='Manatuto-Natabora',link_code='A09-03', link_start_name='Laclubar (Junction C15)', link_end_name='Mane hat',carriageway_width=3.100,funding_source='ADB', project='ADB RNSUP 2014-2020',surface_type_id=1,pavement_class_id=2,road_status_id=2,technical_class_id=6,traffic_level='L',surface_condition='4',administrative_area='Laclubar' WHERE id=11;
UPDATE assets_road SET road_code='A09', road_name='Manatuto-Natabora',link_code='A09-04', link_start_name='Mane Hat', link_end_name='Natarbora (Junction A7)',carriageway_width=4.200,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='L',surface_condition='3',administrative_area='Mane Hat' WHERE id=37;
UPDATE assets_road SET road_code='A10', road_name='Gleno-Lourba',link_code='A10-01', link_start_name='Gleno (Junction A04 )', link_end_name='Lourba (A12 Junction)',carriageway_width=3.500,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='L',surface_condition='3',administrative_area='Gleno' WHERE id=10;
UPDATE assets_road SET road_code='A11', road_name='Ermera-Maliana',link_code='A11-01', link_start_name='Ermera (Junction A04)', link_end_name='Maliana (Junction A03A12)',carriageway_width=3.500,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='L',surface_condition='4',administrative_area='Ermera' WHERE id=26;
UPDATE assets_road SET road_code='A12', road_name='Oeleu-Zumalai',link_code='A12-01', link_start_name='Maliana (A3 Juction)', link_end_name='Oeleu (Junction A16)',carriageway_width=4.600,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='M',surface_condition='2',administrative_area='Maliana' WHERE id=38;
UPDATE assets_road SET road_code='A12', road_name='Oeleu-Zumalai',link_code='A12-02', link_start_name='Oeleu (Junction A16)', link_end_name='Lourba (Junction A10)',carriageway_width=4.600,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='M',surface_condition='4',administrative_area='Oeleu' WHERE id=39;
UPDATE assets_road SET road_code='A12', road_name='Oeleu-Zumalai',link_code='A12-03', link_start_name='Lourba (A10 Juction)', link_end_name='Zumalai (A2 Junction)',carriageway_width=3.600,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='M',surface_condition='4',administrative_area='Lourba' WHERE id=40;
UPDATE assets_road SET road_code='A13', road_name='Aiassa-Cassa',link_code='A13-01', link_start_name='Aiassa (Junction A5)', link_end_name='Hato Udo (Junction C23)',carriageway_width=3.500,funding_source='TimorGap', project='TimorGap',surface_type_id=9,pavement_class_id=1,road_status_id=4,technical_class_id=6,traffic_level='L',surface_condition='3',administrative_area='Aiassa' WHERE id=18;
UPDATE assets_road SET road_code='A13', road_name='Aiassa-Cassa',link_code='A13-02', link_start_name='Hato Udo (Junction C23)', link_end_name='Cassa (Junction A2)',carriageway_width=3.500,funding_source='TimorGap', project='TimorGap',surface_type_id=9,pavement_class_id=1,road_status_id=4,technical_class_id=6,traffic_level='L',surface_condition='3',administrative_area='Hato Udo' WHERE id=41;
UPDATE assets_road SET road_code='A14', road_name='Natabora-Betano',link_code='A14-01', link_start_name='Natarbora (Junction A9)', link_end_name='Alas (Junction C27)',carriageway_width=3.600,funding_source='TimorGap', project='TimorGap',surface_type_id=9,pavement_class_id=1,road_status_id=4,technical_class_id=6,traffic_level='L',surface_condition='1',administrative_area='Natarbora' WHERE id=14;
UPDATE assets_road SET road_code='A14', road_name='Natabora-Betano',link_code='A14-02', link_start_name='Alas (Junction C27)', link_end_name='Betano (A5)',carriageway_width=3.600,funding_source='TimorGap', project='TimorGap',surface_type_id=9,pavement_class_id=1,road_status_id=4,technical_class_id=6,traffic_level='L',surface_condition='1',administrative_area='Alas' WHERE id=13;
UPDATE assets_road SET road_code='A15', road_name='Suai-Uemassa',link_code='A15-01', link_start_name='Suai (Junction C21)', link_end_name='Tilomar (Junction A16)',carriageway_width=4.300,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='L',surface_condition='1',administrative_area='Suai' WHERE id=43;
UPDATE assets_road SET road_code='A15', road_name='Suai-Uemassa',link_code='A15-02', link_start_name='Tilomar (Junction A16)', link_end_name='Uemassa (Indonesian Border)',carriageway_width=4.000,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='M',surface_condition='1',administrative_area='Tilomar' WHERE id=20;
UPDATE assets_road SET road_code='A16', road_name='Oeleu-Tilomar',link_code='A16-01/A16-02', link_start_name='Oeleu (Junction A12)', link_end_name='Tilomar (Junction A15)',carriageway_width=3.600,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='L',surface_condition='4',administrative_area='Oeleu' WHERE id=42;
UPDATE assets_road SET road_code='A17', road_name='Pante Macassar-Oesilo',link_code='A17-01', link_start_name='Pante Macasar', link_end_name='Oesilo',carriageway_width=4.000,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='M',surface_condition='2',administrative_area='Pante Macasar' WHERE id=24;
UPDATE assets_road SET road_code='A18', road_name='Pante Macassar-Citrana',link_code='A18-01', link_start_name='Pante Macasar', link_end_name='Citrana',carriageway_width=4.000,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='M',surface_condition='2',administrative_area='Pante Macasar' WHERE id=23;
UPDATE assets_road SET road_code='A19', road_name='Pante Macassar-Sacato',link_code='A19-01', link_start_name='Pante Macasar', link_end_name='Sakato',funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=6,traffic_level='M',surface_condition='2',administrative_area='Pante Macasar' WHERE id=25;
UPDATE assets_road SET road_code='C01', road_name='Lospalos-Lore-Iliomar', link_start_name='Lospalos', link_end_name='Iliomar (Junction A8)',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=7,traffic_level='L',surface_condition='3',administrative_area='Lospalos' WHERE id=65;
UPDATE assets_road SET road_code='C02', road_name='Trisulu-Tutuala', link_start_name='Fuiloro (Junction A8)', link_end_name='Tutuala',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=7,traffic_level='L',surface_condition='3',administrative_area='Fuiloro' WHERE id=66;
UPDATE assets_road SET road_code='C03', road_name='Com-Trisulu', link_start_name='Com (A1)', link_end_name='Trisula (Junction C2)',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,road_status_id=2,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Com' WHERE id=67;
UPDATE assets_road SET road_code='C04', road_name='Buihomao-Luro', link_start_name='Buihomao (A1)', link_end_name='Luro (A8)',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,technical_class_id=7,traffic_level='L',surface_condition='3',administrative_area='Buihomao' WHERE id=72;
UPDATE assets_road SET road_code='C05', road_name='Luca-Dilor (Lacluta)', link_start_name='Luca (A7)', link_end_name='Dilor (Lacluta)',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Luca' WHERE id=68;
UPDATE assets_road SET road_code='C06', road_name='Mulia-Ossu',link_code='C06-01/C06-02/C06-03', link_start_name='Mulia (A1)', link_end_name='Ossu (A6 via Quilicai)',carriageway_width=3.000,funding_source='-',surface_type_id=1,pavement_class_id=2,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Mulia' WHERE id=78;
UPDATE assets_road SET road_code='C07', road_name='Uatulari-Laisorulai', link_start_name='Uatulari', link_end_name='Laisorulai (via Abana)',funding_source='-',surface_type_id=2,pavement_class_id=2,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='1',administrative_area='Uatulari' WHERE id=51;
UPDATE assets_road SET road_code='C08', road_name='Laga-Uatucarbau',link_code='C08-01/C08-02', link_start_name='Laga', link_end_name='Uatucarbau',carriageway_width=3.000,funding_source='-',surface_type_id=1,pavement_class_id=2,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Laga' WHERE id=80;
UPDATE assets_road SET road_code='C09', road_name='Atauro Vila - Biqueli', link_start_name='Atauro Vila', link_end_name='Biqueli',carriageway_width=3.000,funding_source='-',surface_type_id=2,pavement_class_id=2,technical_class_id=7,traffic_level='L',surface_condition='2',administrative_area='Atauro Vila' WHERE id=73;
UPDATE assets_road SET road_code='C10', road_name='Aileu-Ermera', link_start_name='Aileu (A2)', link_end_name='Ermera (A4)',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Aileu' WHERE id=64;
UPDATE assets_road SET road_code='C11', road_name='Be''eluru-Aileu Vila',link_code='C11-01/C11-02', link_start_name='Be''eluru (A2)', link_end_name='Aileu Vila (A2)',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Be''eluru' WHERE id=79;
UPDATE assets_road SET road_code='C13', road_name='Ermera-Fatubesi', link_start_name='Ermera', link_end_name='Fatubesi',carriageway_width=3.000,funding_source='EU',surface_type_id=9,pavement_class_id=1,road_status_id=2,technical_class_id=7,traffic_level='L',surface_condition='3',administrative_area='Ermera' WHERE id=50;
UPDATE assets_road SET road_code='C14', road_name='Remixio-Laclo', link_start_name='Remixio', link_end_name='Laclo',carriageway_width=3.000,funding_source='-',surface_type_id=1,pavement_class_id=2,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Remixio' WHERE id=63;
UPDATE assets_road SET road_code='C15', road_name='Lei-Laclubar', link_start_name='Lei (A9)', link_end_name='Laclubar',carriageway_width=3.000,funding_source='RDTL',surface_type_id=9,pavement_class_id=1,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='3',administrative_area='Lei' WHERE id=62;
UPDATE assets_road SET road_code='C16', road_name='Tokoluli-Bazartete', link_start_name='Tokoluli (A4)', link_end_name='Bazartete',carriageway_width=3.000,funding_source='EU',surface_type_id=1,pavement_class_id=2,road_status_id=2,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Tokoluli' WHERE id=77;
UPDATE assets_road SET road_code='C17', road_name='Bazartete-Aipelo', link_start_name='Aipelo (A3)', link_end_name='Bazartete',carriageway_width=3.000,funding_source='EU',surface_type_id=9,pavement_class_id=1,road_status_id=2,technical_class_id=7,traffic_level='L',surface_condition='3',administrative_area='Aipelo' WHERE id=61;
UPDATE assets_road SET road_code='C18', road_name='Lacluta-Korlule', link_start_name='Lacluta (A3)', link_end_name='Korlule (A11)',carriageway_width=3.000,funding_source='-',surface_type_id=1,pavement_class_id=2,road_status_id=2,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Lacluta' WHERE id=49;
UPDATE assets_road SET road_code='C19', road_name='Bauqia-Passabe', link_start_name='Bauqia (A17)', link_end_name='Passabe',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Bauqia' WHERE id=60;
UPDATE assets_road SET road_code='C20', road_name='Oesilo-Tumio', link_start_name='Oesileo', link_end_name='Tumio',carriageway_width=3.000,funding_source='-',surface_type_id=2,pavement_class_id=1,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='3',administrative_area='Oesileo' WHERE id=59;
UPDATE assets_road SET road_code='C21', road_name='Suai-Fatululic', link_start_name='Suai (A2A15)', link_end_name='Fatululik (A16)',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='3',administrative_area='Suai' WHERE id=71;
UPDATE assets_road SET road_code='C22', road_name='Letefoho-Hatubuilico', link_start_name='Letefoho (A10)', link_end_name='Hatu Builico (C24)',carriageway_width=3.000,funding_source='WB',surface_type_id=1,pavement_class_id=2,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Letefoho' WHERE id=58;
UPDATE assets_road SET road_code='C23', road_name='Hato Udo-Ainaro', link_start_name='Hato Udo (A13)', link_end_name='Ainaro (A2)',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Hato Udo' WHERE id=56;
UPDATE assets_road SET road_code='C24', road_name='Hatubuilico-Nunumogue', link_start_name='Hatubuilico (C22C25)', link_end_name='Nunumogue',funding_source='WB',surface_type_id=1,pavement_class_id=2,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Hatubuilico' WHERE id=76;
UPDATE assets_road SET road_code='C25', road_name='Maubisse-Hatubuilico', link_start_name='Maubisse (A2)', link_end_name='Hatubuilico (C24C22)',carriageway_width=3.000,funding_source='WB',surface_type_id=9,pavement_class_id=1,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Maubisse' WHERE id=57;
UPDATE assets_road SET road_code='C26', road_name='Maubisse-Turiscai', link_start_name='Maubisse (A2)', link_end_name='Turiscai',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Maubisse' WHERE id=70;
UPDATE assets_road SET road_code='C27', road_name='Turiscai-Alas', link_start_name='Alas (C31)', link_end_name='Turiscai (C26)',carriageway_width=3.000,funding_source='-',surface_type_id=1,pavement_class_id=2,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Alas' WHERE id=75;
UPDATE assets_road SET road_code='C28', road_name='Dotic-Alas', link_start_name='Alas', link_end_name='Weberek (A14)',carriageway_width=3.000,funding_source='-',surface_type_id=1,pavement_class_id=2,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Alas' WHERE id=54;
UPDATE assets_road SET road_code='C29', road_name='Mane Hat-Soibada', link_start_name='Mane Hat (A9)', link_end_name='Soibada (C30)',carriageway_width=3.000,funding_source='-',surface_type_id=1,pavement_class_id=2,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Mane Hat' WHERE id=52;
UPDATE assets_road SET road_code='C30', road_name='Laclubar-Soibada', link_start_name='Laclubar (C15)', link_end_name='Soibada (C29)',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Laclubar' WHERE id=55;
UPDATE assets_road SET road_code='C31', road_name='Weberek-Alas', link_start_name='Alas (C27)', link_end_name='Weberek (A14)',carriageway_width=3.000,funding_source='-',surface_type_id=1,pavement_class_id=2,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='4',administrative_area='Alas' WHERE id=74;
UPDATE assets_road SET road_code='C32', road_name='Beco-Lolotoe', link_start_name='Lolotoe (A16)', link_end_name='Beco (A2)',carriageway_width=3.000,funding_source='-',surface_type_id=9,pavement_class_id=1,road_status_id=3,technical_class_id=7,traffic_level='L',surface_condition='2',administrative_area='Lolotoe' WHERE id=53;
