# Generated by Django 2.2.4 on 2020-03-13 00:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EstradaRoad",
            fields=[
                ("road_code", models.TextField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=32751
                    ),
                ),
            ],
        ),
    ]
