# Generated by Django 2.2.4 on 2020-02-21 05:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0027_auto_20200114_0742"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstradaRoad",
            fields=[
                ("road_code", models.TextField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=32751
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoadCorrection",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="assets.Road",
                    ),
                ),
                ("road_code", models.TextField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=32751
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopoRoad",
            fields=[
                ("road_code", models.TextField(primary_key=True, serialize=False)),
                ("topo_geom", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(name="toporoad", options={"managed": False},),
    ]
