# Generated by Django 2.2.4 on 2020-03-10 01:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topology", "0001_estradaroad_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roadhash",
            fields=[
                (
                    "road",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="assets.Road",
                    ),
                ),
                ("geohash", models.UUIDField()),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="SinglepartDump",
            fields=[
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        dim=32751, srid=4326, verbose_name="LineString"
                    ),
                ),
                ("geohash", models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="InputRoad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geohash", models.UUIDField(blank=True, null=True)),
                (
                    "blacklist",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a Blacklisted, never-include-road. False if this is a road to include in Topology creation.",
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        default=False,
                        help_text="True if this code is not to be included now. Like blacklist but temporary.",
                    ),
                ),
                ("road_code", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoadCorrectionCodeChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geohash", models.UUIDField(blank=True, null=True)),
                ("dest_road_code", models.TextField()),
                (
                    "part",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=32751
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoadCorrectionSegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geohash", models.UUIDField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=32751
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoadCorrectionTrim",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geohash", models.UUIDField(blank=True, null=True)),
                (
                    "patch",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=32751
                    ),
                ),
            ],
        ),
    ]
