# Generated by Django 2.2.4 on 2020-02-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topology", "0002_roadcorrectionsegment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadcorrectionsegment",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
