# Generated by Django 2.2.4 on 2020-02-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topology", "0003_auto_20200222_1514"),
    ]

    operations = [
        migrations.DeleteModel(name="RoadCorrection",),
    ]
