# Generated by Django 2.2.4 on 2020-03-03 05:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topology", "0003_auto_20200227_0134"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadAlternateCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_road_code", models.TextField()),
                ("dest_road_code", models.TextField()),
                (
                    "part",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=32751
                    ),
                ),
            ],
        ),
    ]
