# Generated by Django 2.2.4 on 2020-02-23 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0027_auto_20200114_0742"),
        ("topology", "0004_delete_roadcorrection"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopoInputRoads",
            fields=[
                (
                    "road_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="assets.Road",
                    ),
                ),
                (
                    "blacklist",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a Blacklisted, never-include-road. False if this is a road to include in Topology creation.",
                    ),
                ),
            ],
        ),
    ]
