# Generated by Django 2.2.4 on 2020-02-23 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topology", "0005_topoinputroads"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topoinputroads", old_name="road_id", new_name="road",
        ),
    ]
