# Generated by Django 2.2.4 on 2020-02-23 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0027_auto_20200114_0742"),
        ("topology", "0006_auto_20200223_0529"),
    ]

    operations = [
        migrations.RenameModel(old_name="TopoInputRoads", new_name="InputRoad",),
    ]
