# Generated by Django 2.2.4 on 2020-02-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topology", "0007_auto_20200223_0529"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputroad",
            name="road_code",
            field=models.TextField(
                blank=True,
                help_text="Override the road_code from the assets table where required",
                null=True,
            ),
        ),
    ]
