# Generated by Django 2.2.4 on 2020-02-24 02:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topology", "0008_inputroad_road_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intersection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("road_id_a", models.IntegerField()),
                ("road_id_b", models.IntegerField()),
                (
                    "intersection",
                    django.contrib.gis.db.models.fields.PointField(srid=32751),
                ),
            ],
        ),
    ]
