# Generated by Django 2.2.4 on 2020-02-24 05:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topology", "0009_intersection"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadcorrectionsegment",
            name="patch",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=32751
            ),
        ),
    ]
