# Generated by Django 2.2.4 on 2020-02-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topology", "0010_roadcorrectionsegment_patch"),
    ]

    operations = [
        migrations.RemoveField(model_name="roadcorrectionsegment", name="deletion",),
    ]
