# Generated by Django 2.2.4 on 2020-02-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topology", "0011_remove_roadcorrectionsegment_deletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputroad",
            name="disabled",
            field=models.BooleanField(
                default=False,
                help_text="True if this code is not to be included now. Like blacklist but temporary.",
            ),
        ),
    ]
