# Generated by Django 2.2.4 on 2020-02-10 09:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# contracts.migrations.0010_auto_20200210_0226
# contracts.migrations.0012_contract_choices


DOCTYPES = {
    "project": [
        "Drawings / design documents",
        "BoQ (bill of quantities)",
        "Construction schedule",
        "Social and safeguard specification",
        "Environment licenses",
        "Letters of approval",
        "Confirmation of funds",
        "CPV (commitment and payment voucher)",
    ],
    "tender": [
        "Bid documents",
        "Bid documents approval",
        "Tender announcement",
        "Bid evaluation criteria",
        "List of presented bids",
        "Proposal (winner bid)",
        "Evaluation report",
        "Contract approval",
        "Contract award - letter acceptance",
    ],
    "contract": [
        "Contract (signed)",
        "Amendment to contract request",
        "Amendment to contract rejected / approved",
        "Amendment to contract signed",
        "Interim payment request",
        "Invoice",
        "Proforma invoice",
        "Payment approval",
        "Transaction certificate",
        "Request of final payment",
        "Taking over notice",
        "Inspection report",
        "Final inspection report (provisional handover)",
        "Final inspection report (after DLP)",
        "Muster roll",
    ],
    "company": [
        "TIN certificate",
        "Company registry (registo comercial)",
        "Licenca de actividade",
        "Certificado de nao dividas Financas",
        "Electoral card of the representative",
    ],
}

DONORS = [
    "JICA",
    "ADB",
    "ILO",
    "World Bank",
    "European Union",
]

FUNDING_SOURCES = [
    "Infrastructure fund",
    "Line Ministries",
]

INSPECTION_ENTITIES = [
    "Construction Department",
    "Maintenance Department",
    "Highway Department",
    "Project Department",
    "Evaluation and Analysis Department",
    "Cooperation Department",
    "Municipal office",
]

TYPEOFWORK_CHOICES = [
    "Routine maintenance",
    "Periodic maintenance",
    "Rehabilitation",
    "Reconstruction",
]

PROGRAM_CHOICES = [
    "Programa de estradas",
    "Programa de pontes",
    "Programa de manutenção e reabilitação de infraestruturas",
    "Programa de desenvolvimento tasi mane",
]

PROJECT_STATUS_CHOICES = [
    "Planning",
    "Submitted - waiting for approval",
    "Project approved",
    "Project rejected",
]

TENDER_STATUS_CHOICES = [
    "Tender preparation",
    "Tender announcement / Bid submission",
    "Evaluation",
    "Contract preparation",
    "Contract signed",
    "Tender canceled",
]


def initial_contract_choices(apps, schema_editor):
    ContractPaymentDonor = apps.get_model("contracts", "ContractPaymentDonor")
    {ContractPaymentDonor(name=d).save() for d in DONORS}

    ContractPaymentSource = apps.get_model("contracts", "ContractPaymentSource")
    {ContractPaymentSource(name=d).save() for d in FUNDING_SOURCES}

    ContractInspectionEntity = apps.get_model("contracts", "ContractInspectionEntity")
    {ContractInspectionEntity(name=d).save() for d in INSPECTION_ENTITIES}


def initial_tender_choices(apps, schema_editor):
    model = apps.get_model("contracts", "TenderStatus")
    {model(name=d).save() for d in TENDER_STATUS_CHOICES}


def initial_status_choices(apps, schema_editor):
    model = apps.get_model("contracts", "ProjectStatus")
    {model(name=d).save() for d in PROJECT_STATUS_CHOICES}


def initial_typeofwork_choices(apps, schema_editor):
    model = apps.get_model("contracts", "TypeOfWork")
    {model(name=d).save() for d in TYPEOFWORK_CHOICES}


def initial_program_choices(apps, schema_editor):
    model = apps.get_model("contracts", "Program")
    {model(name=d).save() for d in PROGRAM_CHOICES}


def initial_document_types(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    model = apps.get_model("contracts", "ContractDocumentType")
    for category, doctypes_for_category in DOCTYPES.items():
        for dt in doctypes_for_category:
            instance = model(name=dt, category=category)
            instance.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("plan", "Planning"),
                            ("sub", "Submitted"),
                            ("wait", "Waiting for approval"),
                            ("app", "Project approved"),
                            ("rej", "Project Rejected"),
                            ("can", "Project canceled"),
                        ]
                    ),
                ),
                ("description", models.TextField()),
                ("funding_source", models.CharField(max_length=128)),
                ("construction_period_end", models.DateField(default=None)),
                ("construction_period_start", models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("progress", models.IntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="contracts.Project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectBudget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="contracts.Project",
                    ),
                ),
                ("end_date", models.DateField(default=None)),
                ("start_date", models.DateField(default=None)),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectAsset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_code", models.CharField(max_length=128)),
                (
                    "asset_end_chainage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="Enter chainage for asset ending point",
                        max_digits=12,
                        null=True,
                        verbose_name="Asset End Chainage",
                    ),
                ),
                (
                    "asset_start_chainage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="Enter chainage for asset starting point",
                        max_digits=12,
                        null=True,
                        verbose_name="Asset Start Chainage",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="contracts.Project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[("document", "Dokumentu")], max_length=256
                    ),
                ),
                ("document_date", models.DateField(blank=True, null=True)),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="documents", to="contracts.Project"
                    ),
                ),
                (
                    "content",
                    models.FileField(default=None, upload_to="contract_documents/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractDocumentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("category", models.CharField(max_length=8)),
            ],
        ),
        migrations.RunPython(initial_document_types,),
        migrations.AlterField(
            model_name="contractdocument",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contracts.ContractDocumentType",
            ),
        ),
        migrations.AlterField(
            model_name="projectmilestone",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Tender",
            fields=[
                ("code", models.SlugField(primary_key=True, serialize=False)),
                ("announcement_date", models.DateField(blank=True, null=True)),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("tendering_companies", models.IntegerField(blank=True, null=True)),
                ("evaluation_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("tender_preparation", "Tender preparation"),
                            ("announcement", "Tender announcement / Bid submission"),
                            ("evaluation", "Evaluation"),
                            ("contract_preparation", "Contract preparation"),
                            ("signed", "Contract signed"),
                            ("cancelled", "Tender canceled"),
                        ],
                        default="preparation",
                        max_length=128,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("address", models.TextField(blank=True, max_length=1024, null=True)),
                ("phone", models.CharField(blank=True, max_length=256, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("TIN", models.IntegerField(blank=True, null=True)),
                ("iban", models.CharField(blank=True, max_length=256, null=True)),
                ("rep_name", models.CharField(blank=True, max_length=256, null=True)),
                ("rep_phone", models.CharField(blank=True, max_length=256, null=True)),
                ("rep_email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContractStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="ContractSupervisor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("phone", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_code", models.SlugField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "contract_total_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("defect_liability_days", models.IntegerField(blank=True, null=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="contractor_for",
                        to="contracts.Company",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="contracts.ContractStatus",
                    ),
                ),
                (
                    "subcontractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sub_contractor_for",
                        to="contracts.Company",
                    ),
                ),
                (
                    "supervisors",
                    models.ManyToManyField(
                        blank=True, to="contracts.ContractSupervisor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractInspectionEntity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="ContractPaymentDonor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="ContractPaymentSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="ContractPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.Company",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.ContractPaymentDonor",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.ContractPaymentSource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractInspection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "progress",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("dlp_start_date", models.DateField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.ContractInspectionEntity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractAmendment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_total_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.Contract",
                    ),
                ),
            ],
        ),
        migrations.RunPython(initial_contract_choices,),
        migrations.AddField(
            model_name="contractinspection",
            name="contract",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts.Contract",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contractdocument",
            name="content",
            field=models.FileField(upload_to="contract_documents/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="construction_period_end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="construction_period_start",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="projectbudget", name="end_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="projectbudget", name="start_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="projectmilestone",
            name="date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SocialSafeguardData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("report", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TypeOfWork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="code",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="program",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="contracts.Program",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="type_of_work",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="contracts.TypeOfWork",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TenderStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="code",
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contracts.ProjectStatus",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="contracts.TenderStatus"
            ),
        ),
        migrations.CreateModel(
            name="FundingSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="funding_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contracts.FundingSource",
            ),
        ),
        migrations.CreateModel(
            name="ContractBudget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("value", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.Contract",
                    ),
                ),
            ],
        ),
        migrations.RunPython(initial_typeofwork_choices),
        migrations.RunPython(initial_program_choices),
        migrations.RunPython(initial_status_choices),
        migrations.RunPython(initial_tender_choices),
    ]
