# Generated by Django 2.2.4 on 2020-02-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdocument",
            name="contracts",
            field=models.ManyToManyField(
                related_name="documents", to="contracts.Contract"
            ),
        ),
        migrations.AddField(
            model_name="contractdocument",
            name="tenders",
            field=models.ManyToManyField(
                related_name="documents", to="contracts.Tender"
            ),
        ),
    ]
