# Generated by Django 2.2.4 on 2020-02-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_auto_20200213_0155"),
    ]

    operations = [
        migrations.RemoveField(model_name="socialsafeguarddata", name="date",),
        migrations.AddField(
            model_name="company", name="woman_led", field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="socialsafeguarddata",
            name="month",
            field=models.IntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="socialsafeguarddata",
            name="year",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
