# Generated by Django 2.2.4 on 2020-02-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_auto_20200213_0222"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="socialsafeguarddata",
            constraint=models.CheckConstraint(
                check=models.Q(year__gte=2010), name="year_gt_2010"
            ),
        ),
        migrations.AddConstraint(
            model_name="socialsafeguarddata",
            constraint=models.CheckConstraint(
                check=models.Q(year__lte=2100), name="year_gt_2100"
            ),
        ),
        migrations.AddConstraint(
            model_name="socialsafeguarddata",
            constraint=models.UniqueConstraint(
                fields=("year", "month"), name="unique_month"
            ),
        ),
    ]
