# Generated by Django 2.2.4 on 2020-02-13 07:16

from django.db import migrations

DOCTYPES = {"contract": ["Notice to Proceed", "Warning letter", "Termination letter"]}


def initial_document_types(apps, schema_editor):
    model = apps.get_model("contracts", "ContractDocumentType")
    for category, doctypes_for_category in DOCTYPES.items():
        for dt in doctypes_for_category:
            instance = model(name=dt, category=category)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_contracttender_projectcontract_projecttender"),
    ]

    operations = [migrations.RunPython(initial_document_types)]
