# Generated by Django 2.2.4 on 2020-02-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20200219_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Naran Projetu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.Program', verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.TypeOfWork', verbose_name='Type of Work'),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='asset_code',
            field=models.CharField(max_length=128, verbose_name='Sasan (aset)'),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='asset_end_chainage',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Enter chainage for asset ending point', max_digits=12, null=True, verbose_name='End Chainage'),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='asset_start_chainage',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Enter chainage for asset starting point', max_digits=12, null=True, verbose_name='Start Chainage'),
        ),
    ]
