# Generated by Django 2.2.4 on 2020-02-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0011_auto_20200220_0615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingsource",
            name="name",
            field=models.CharField(
                max_length=256, unique=True, verbose_name="Funding Source"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Project Name"),
        ),
        migrations.AlterField(
            model_name="projectasset",
            name="asset_code",
            field=models.CharField(max_length=128, verbose_name="Asset"),
        ),
    ]
