# Generated by Django 2.2.4 on 2020-03-03 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_remove_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.ProjectStatus', verbose_name='Project Status'),
        ),
    ]
