# Generated by Django 2.2.4 on 2020-03-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0015_auto_20200303_0742"),
        ("contracts", "0014_project_status_verbose_name"),
    ]

    operations = []
