# Generated by Django 2.2.4 on 2020-03-04 02:54

# This change added because we separate these fields out from Create Project form, and save was failing

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0016_merge_20200303_0746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="construction_period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="construction_period_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
