# Generated by Django 2.2.4 on 2020-03-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0017_contract_dates_notrequired"),
    ]

    operations = [
        migrations.RemoveField(model_name="projectbudget", name="estimated_value",),
    ]
