# Generated by Django 2.2.4 on 2020-03-05 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_auto_20200305_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='contracts.Tender'),
        ),
    ]
