# Generated by Django 2.2.4 on 2020-03-12 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0026_contract_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="contract", name="supervisors",),
        migrations.AddField(
            model_name="contractsupervisor",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contracts.Contract",
            ),
            preserve_default=False,
        ),
    ]
