# Generated by Django 2.2.4 on 2020-03-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_contract_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_total_value',
        ),
    ]
