# Generated by Django 2.2.4 on 2020-03-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0029_add_contract_budget_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractamendment", name="contract_total_value",
        ),
    ]
