# Generated by Django 2.2.4 on 2020-03-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0031_update_contract_amendment"),
    ]

    operations = [
        migrations.RemoveField(model_name="projectcontract", name="contract",),
        migrations.RemoveField(model_name="projectcontract", name="project",),
        migrations.DeleteModel(name="ContractTender",),
        migrations.DeleteModel(name="ProjectContract",),
    ]
