# Generated by Django 2.2.4 on 2020-03-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0032_delete_m2m_models"),
    ]

    operations = [
        migrations.RemoveField(model_name="contractinspection", name="dlp_start_date",),
        migrations.AddField(
            model_name="contractinspection",
            name="defect_liability_period",
            field=models.NullBooleanField(choices=[(True, "Yes"), (False, "No")]),
        ),
    ]
