# Generated by Django 2.2.4 on 2020-03-13 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0033_update_contract_inspection"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractpayment",
            name="contract",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts.Contract",
            ),
            preserve_default=False,
        ),
    ]
