# Generated by Django 2.2.4 on 2020-03-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0037_add_project_budget_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="construction_period_end",
            new_name="start_date",
        ),
        migrations.RemoveField(model_name="project", name="construction_period_start",),
        migrations.AddField(
            model_name="project",
            name="duration",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Duration (days)"
            ),
        ),
    ]
