# Generated by Django 2.2.4 on 2020-03-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0038_edit_project_construction_schedule_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.Tender', verbose_name='Associated tender'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='contracts.Tender', verbose_name='Associated projects'),
        ),
    ]
