# Generated by Django 2.2.4 on 2020-03-30 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0039_update_verbose_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmilestone",
            name="progress",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Physical progress (%)",
            ),
        ),
    ]
