# Generated by Django 2.2.4 on 2020-03-30 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0040_field_validator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="defect_liability_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Defect liability period (days)"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="duration",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Duration (days)"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Contract end date"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Contract start date"
            ),
        ),
        migrations.AlterField(
            model_name="contractmilestone",
            name="progress",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Physical progress (%)",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="amendment_description",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Description (Reasons for Variations)",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="amendment_duration",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Contract duration"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="amendment_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Contract start date"
            ),
        ),
    ]
