# Generated by Django 2.2.4 on 2020-04-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0043_model_required_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdocument",
            name="companies",
            field=models.ManyToManyField(
                related_name="documents", to="contracts.Company"
            ),
        ),
    ]
