# Generated by Django 2.2.4 on 2020-04-13 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0045_project_asset_verbose_name'),
        ('contracts', '0045_contract_documents_m2m_relation'),
    ]

    operations = [
    ]
