# Generated by Django 2.2.4 on 2020-04-22 02:47

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0048_company_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="projectasset", name="asset_code",),
        migrations.AddField(
            model_name="projectasset",
            name="asset_id",
            field=models.CharField(
                db_index=True,
                help_text="Select project's asset",
                max_length=15,
                default="",
                validators=[contracts.models.no_spaces],
                verbose_name="Asset Id",
            ),
        ),
    ]
