# Generated by Django 2.2.4 on 2020-04-28 02:10

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0050_unique_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectasset",
            name="asset_id",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Select project's asset",
                max_length=30,
                validators=[contracts.models.no_spaces],
                verbose_name="Asset Id",
            ),
        ),
    ]
