# Generated by Django 2.2.4 on 2020-04-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0051_project_asset_id_bigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractamendment",
            name="year",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                    (2023, 2023),
                    (2024, 2024),
                    (2025, 2025),
                    (2026, 2026),
                    (2027, 2027),
                    (2028, 2028),
                    (2029, 2029),
                    (2030, 2030),
                ],
                help_text="Select year",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contractbudget",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                    (2023, 2023),
                    (2024, 2024),
                    (2025, 2025),
                    (2026, 2026),
                    (2027, 2027),
                    (2028, 2028),
                    (2029, 2029),
                    (2030, 2030),
                ],
                help_text="Select year",
            ),
        ),
    ]
