# Generated by Django 2.2.4 on 2020-05-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0054_remove_physical_progress_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingDonor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, unique=True, verbose_name="Donor"),
                ),
            ],
        ),
    ]
