# Generated by Django 2.2.4 on 2020-05-28 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0055_funding_donor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractpayment",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contracts.FundingDonor",
            ),
        ),
        migrations.AlterField(
            model_name="contractpayment",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contracts.FundingSource",
            ),
        ),
        migrations.AlterField(
            model_name="fundingsource",
            name="name",
            field=models.CharField(max_length=256, unique=True, verbose_name="Source"),
        ),
        migrations.AlterField(
            model_name="project",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose the donor",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contracts.FundingDonor",
            ),
        ),
        migrations.DeleteModel(name="ContractPaymentDonor",),
        migrations.DeleteModel(name="ContractPaymentSource",),
        migrations.DeleteModel(name="ProjectDonor",),
    ]
