# Generated by Django 2.2.4 on 2020-07-08 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0057_tender_primary_key"),
    ]

    operations = [
        migrations.RemoveField(model_name="contractdocument", name="companies",),
        migrations.AddField(
            model_name="contractdocument",
            name="companies",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="contracts.Company",
            ),
        ),
        migrations.RemoveField(model_name="contractdocument", name="contracts",),
        migrations.AddField(
            model_name="contractdocument",
            name="contracts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="contracts.Contract",
            ),
        ),
        migrations.RemoveField(model_name="contractdocument", name="projects",),
        migrations.AddField(
            model_name="contractdocument",
            name="projects",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="contracts.Project",
            ),
        ),
        migrations.RemoveField(model_name="contractdocument", name="tenders",),
        migrations.AddField(
            model_name="contractdocument",
            name="tenders",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="contracts.Tender",
            ),
        ),
    ]
