# Generated by Django 2.2.4 on 2020-08-10 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0058_documents_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contractor",
            field=models.ForeignKey(
                help_text="Select a company from the list",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="contractor_for",
                to="contracts.Company",
            ),
        ),
    ]
