# Generated by Django 2.2.4 on 2020-08-14 03:35

from django.db import migrations, models
import django.db.models.deletion
import contracts.models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("contracts", "0059_contracts_require_contractor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectasset",
            name="asset_id",
            field=models.CharField(
                default="",
                help_text="Select project's asset",
                max_length=30,
                validators=[contracts.models.no_spaces],
                verbose_name="Asset Id",
            ),
        ),
        migrations.AddField(
            model_name="projectasset",
            name="asset_pk",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectasset",
            name="asset_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_type",
                to="contenttypes.ContentType",
            ),
        ),
    ]
