# Generated by Django 2.2.4 on 2019-11-25 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import protected_downloads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "asset",
                    protected_downloads.models.VariableStorageFileField(upload_to=""),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DownloadAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downloaded", models.DateTimeField(auto_now=True)),
                (
                    "download",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="protected_downloads.Download",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
