# Generated by Django 2.2.4 on 2019-11-25 07:07

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/petercoward/Devel/roads/roads/IRMIS/protected_downloads'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded', models.DateTimeField(auto_now=True)),
                ('download', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='protected_downloads.Download')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
