# Generated by Django 2.2.3 on 2019-08-06 04:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_road_geometry_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Shapefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='media/shapefiles')),
                ('srs', models.CharField(max_length=255)),
                ('file_update_date', models.DateField(verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='road',
            name='id',
        ),
        migrations.RemoveField(
            model_name='road',
            name='name',
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Feature')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='The area of the bridge', null=True, srid=4326, verbose_name='Name')),
            ],
            bases=('assets.feature',),
        ),
        migrations.AddField(
            model_name='feature',
            name='shapefile',
            field=models.ForeignKey(on_delete='', to='assets.Shapefile'),
        ),
        migrations.AddField(
            model_name='road',
            name='feature_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Feature'),
            preserve_default=False,
        ),
    ]
