# Generated by Django 2.2.3 on 2019-08-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_road_geometry_help'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Road',
        ),
    ]
