# Generated by Django 2.2.3 on 2019-08-06 06:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_road_geometry_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shapefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(null=True, upload_to='media/shapefiles')),
                ('srs', models.CharField(max_length=255)),
                ('file_update_date', models.DateField(verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='The area of the bridge', null=True, srid=4326, verbose_name='Name')),
                ('shapefile', models.ForeignKey(on_delete='', to='assets.Shapefile')),
            ],
        ),
        migrations.AddField(
            model_name='road',
            name='shapefile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Shapefile'),
        ),
    ]
