# Generated by Django 2.2.3 on 2019-08-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20190806_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapefile',
            name='srs',
        ),
        migrations.AddField(
            model_name='shapefile',
            name='feature_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
