# Generated by Django 2.2.3 on 2019-08-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20190807_0602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shapefile',
        ),
    ]
