# Generated by Django 2.2.4 on 2019-08-19 06:56

import assets.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("assets", "0005_auto_20190815_0322")]

    operations = [
        migrations.CreateModel(
            name="MaintenanceNeed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="name"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="code")),
                (
                    "name_tet",
                    models.CharField(max_length=50, null=True, verbose_name="code"),
                ),
                (
                    "name_pt",
                    models.CharField(max_length=50, null=True, verbose_name="code"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=50, null=True, verbose_name="code"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PavementClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="name"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="code")),
                (
                    "name_tet",
                    models.CharField(max_length=50, null=True, verbose_name="code"),
                ),
                (
                    "name_pt",
                    models.CharField(max_length=50, null=True, verbose_name="code"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=50, null=True, verbose_name="code"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoadStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="name"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="code")),
                (
                    "name_tet",
                    models.CharField(max_length=50, null=True, verbose_name="code"),
                ),
                (
                    "name_pt",
                    models.CharField(max_length=50, null=True, verbose_name="code"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=50, null=True, verbose_name="code"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurfaceType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="name"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="code")),
                (
                    "name_tet",
                    models.CharField(max_length=50, null=True, verbose_name="code"),
                ),
                (
                    "name_pt",
                    models.CharField(max_length=50, null=True, verbose_name="code"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=50, null=True, verbose_name="code"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="name"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="code")),
            ],
        ),
        migrations.AddField(
            model_name="road",
            name="administrative_area",
            field=models.CharField(
                default=None,
                max_length=50,
                null=True,
                verbose_name="administrative area",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="carriageway_width",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="carriageway width",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="funding_source",
            field=models.CharField(
                default=None, max_length=50, null=True, verbose_name="funding source"
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="link_code",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                validators=[assets.models.no_spaces],
                verbose_name="link code",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="link_end_chainage",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=12,
                null=True,
                verbose_name="link end chainage",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="link_end_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="link end name"
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="link_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=8,
                null=True,
                verbose_name="link length",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="link_start_chainage",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=12,
                null=True,
                verbose_name="link start chainage",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="link_start_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="link start name"
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="project",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="project"
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="road_code",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                validators=[assets.models.no_spaces],
                verbose_name="road code",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="road_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="road name"
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAT", "National"),
                    ("HIGH", "Highway"),
                    ("MUN", "Municipal"),
                    ("URB", "Urban"),
                    ("RUR", "Rural"),
                ],
                max_length=4,
                null=True,
                verbose_name="road type",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="surface_condition",
            field=models.CharField(
                blank=True,
                choices=[("1", "Good"), ("2", "Fair"), ("3", "Bad"), ("4", "Poor")],
                max_length=1,
                null=True,
                verbose_name="surface condition",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="traffic_level",
            field=models.CharField(
                blank=True,
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="date created"
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="last modified"),
        ),
        migrations.AddField(
            model_name="road",
            name="maintanance_need",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.MaintenanceNeed",
                verbose_name="maintenance need",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="pavement_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.PavementClass",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="pavement class",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="road_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.RoadStatus",
                verbose_name="road status",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="surface_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.SurfaceType",
                verbose_name="surface type",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="technical_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.TechnicalClass",
                verbose_name="technical class",
            ),
        ),
    ]
