# Generated by Django 2.2.4 on 2019-08-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_populate_meta_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='properties_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
