# Generated by Django 2.2.4 on 2019-08-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("assets", "0008_auto_20190820_0032")]

    operations = [
        migrations.AlterField(
            model_name="maintenanceneed",
            name="code",
            field=models.CharField(max_length=3, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="maintenanceneed",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="maintenanceneed",
            name="name_en",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="maintenanceneed",
            name="name_pt",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="maintenanceneed",
            name="name_tet",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="pavementclass",
            name="code",
            field=models.CharField(max_length=3, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="pavementclass",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="pavementclass",
            name="name_en",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="pavementclass",
            name="name_pt",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="pavementclass",
            name="name_tet",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="roadstatus",
            name="code",
            field=models.CharField(max_length=3, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="roadstatus",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="roadstatus",
            name="name_en",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="roadstatus",
            name="name_pt",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="roadstatus",
            name="name_tet",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="surfacetype",
            name="code",
            field=models.CharField(max_length=3, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="surfacetype",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="surfacetype",
            name="name_en",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="surfacetype",
            name="name_pt",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="surfacetype",
            name="name_tet",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="technicalclass",
            name="code",
            field=models.CharField(max_length=3, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="technicalclass",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
    ]
