# Generated by Django 2.2.4 on 2019-08-21 08:42
import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("assets", "0009_fix_names")]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="road_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="road name"
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_code",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[assets.models.no_spaces],
                verbose_name="road code",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="link_code",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[assets.models.no_spaces],
                verbose_name="link code",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="surface_condition",
            field=models.CharField(
                blank=True,
                choices=[("1", "Good"), ("2", "Fair"), ("3", "Poor"), ("4", "Bad")],
                max_length=1,
                null=True,
                verbose_name="surface condition",
            ),
        ),
    ]
