# Generated by Django 2.2.4 on 2019-09-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("assets", "0011_geojson_collation_file")]

    operations = [
        migrations.RenameField(
            model_name="road", old_name="maintanance_need", new_name="maintenance_need"
        )
    ]
