# Generated by Django 2.2.4 on 2019-09-19 06:38

import assets.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("assets", "0013_auto_20190905_0127")]

    operations = [
        migrations.AlterField(
            model_name="maintenanceneed",
            name="code",
            field=models.CharField(max_length=3, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="maintenanceneed",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="maintenanceneed",
            name="name_en",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="maintenanceneed",
            name="name_pt",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="maintenanceneed",
            name="name_tet",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="pavementclass",
            name="code",
            field=models.CharField(max_length=3, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="pavementclass",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="pavementclass",
            name="name_en",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="pavementclass",
            name="name_pt",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="pavementclass",
            name="name_tet",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="road",
            name="administrative_area",
            field=models.CharField(
                default=None,
                help_text="Choose the administrative area of the road",
                max_length=50,
                null=True,
                verbose_name="Administrative Area",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="carriageway_width",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Enter the width (in meters) of the link carriageway",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Carriageway Width",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date Created"
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="funding_source",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Enter the source funding for the road link",
                max_length=50,
                null=True,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="link_code",
            field=models.CharField(
                blank=True,
                help_text="Enter link code according to DRBFC standard",
                max_length=25,
                null=True,
                validators=[assets.models.no_spaces],
                verbose_name="Link Code",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="link_end_chainage",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Enter chainage for link ending point",
                max_digits=12,
                null=True,
                verbose_name="Link End Chainage (Km)",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="link_end_name",
            field=models.CharField(
                blank=True,
                help_text="Enter the name of the link end location (municipal center, administrative post or nearest suco)",
                max_length=150,
                null=True,
                verbose_name="Link End Name",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="link_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Enter road link length (in Km)",
                max_digits=8,
                null=True,
                verbose_name="Link Length",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="link_start_chainage",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Enter chainage for link starting point",
                max_digits=12,
                null=True,
                verbose_name="Link Start Chainage (Km)",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="link_start_name",
            field=models.CharField(
                blank=True,
                help_text="Enter the name of the link start location (municipal center, administrative post or nearest suco)",
                max_length=150,
                null=True,
                verbose_name="Link Start Name",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="maintenance_need",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose the type of maintenace needs for the road link",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.MaintenanceNeed",
                verbose_name="Maintenance Need",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="pavement_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose the pavement class of the road",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.PavementClass",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Pavement Class",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="project",
            field=models.CharField(
                blank=True,
                help_text="Enter road link project name",
                max_length=150,
                null=True,
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_code",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[assets.models.no_spaces],
                verbose_name="Road Code",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_status",
            field=models.ForeignKey(
                blank=True,
                help_text="Enter road link current status",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.RoadStatus",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAT", "National"),
                    ("HIGH", "Highway"),
                    ("MUN", "Municipal"),
                    ("URB", "Urban"),
                    ("RUR", "Rural"),
                ],
                help_text="Choose the administrative class of the road",
                max_length=4,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="surface_condition",
            field=models.CharField(
                blank=True,
                choices=[("1", "Good"), ("2", "Fair"), ("3", "Poor"), ("4", "Bad")],
                help_text="Choose road link surface condition according to the Surface Distress Index (SDI): Good (SDI≤2), fair (2<SDI≤3), poor (3<SDI≤4) or bad (SDI>4)",
                max_length=1,
                null=True,
                verbose_name="Surface Condition",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="surface_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose the type of surface of the road link carriageway",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.SurfaceType",
                verbose_name="Surface Type",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="technical_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose road link technical class according to the 2010 Road Geometric Design Standards, DRBFC standards",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.TechnicalClass",
                verbose_name="Technical Class",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="traffic_level",
            field=models.CharField(
                blank=True,
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                help_text="Choose the traffic volume for the road link",
                max_length=1,
                null=True,
                verbose_name="Traffic Level",
            ),
        ),
        migrations.AlterField(
            model_name="roadstatus",
            name="code",
            field=models.CharField(max_length=3, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="roadstatus",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="roadstatus",
            name="name_en",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="roadstatus",
            name="name_pt",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="roadstatus",
            name="name_tet",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="surfacetype",
            name="code",
            field=models.CharField(max_length=3, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="surfacetype",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="surfacetype",
            name="name_en",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="surfacetype",
            name="name_pt",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="surfacetype",
            name="name_tet",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="technicalclass",
            name="code",
            field=models.CharField(max_length=3, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="technicalclass",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
    ]
