# Generated by Django 2.2.4 on 2019-09-25 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("assets", "0014_road_fieldnames_helptext")]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="maintenance_need",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose the type of maintenace needs for the road link",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.MaintenanceNeed",
                verbose_name="Maintenance Needs",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="project",
            field=models.CharField(
                blank=True,
                help_text="Enter road link project name",
                max_length=150,
                null=True,
                verbose_name="Project Name",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_status",
            field=models.ForeignKey(
                blank=True,
                help_text="Enter road link current status",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.RoadStatus",
                verbose_name="Road Status",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAT", "National"),
                    ("HIGH", "Highway"),
                    ("MUN", "Municipal"),
                    ("URB", "Urban"),
                    ("RUR", "Rural"),
                ],
                help_text="Choose the administrative class of the road",
                max_length=4,
                null=True,
                verbose_name="Road Type",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="surface_condition",
            field=models.CharField(
                blank=True,
                choices=[("1", "Good"), ("2", "Fair"), ("3", "Poor"), ("4", "Bad")],
                help_text="Choose road link surface condition according to the Surface Distress Index (SDI): Good (SDI≤2), fair (2<SDI≤3), poor (3<SDI≤4) or bad (SDI>4)",
                max_length=1,
                null=True,
                verbose_name="Surface Condition (SDI)",
            ),
        ),
    ]
