# Generated by Django 2.2.4 on 2019-10-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("assets", "0017_create_surveys")]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="date_surveyed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date Surveyed"
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="source",
            field=models.CharField(
                default=None,
                help_text="Choose the source of the survey",
                max_length=150,
                null=True,
                verbose_name="Source",
            ),
        ),
    ]
