# Generated by Django 2.2.4 on 2019-10-07 01:29

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_create_surveys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='road',
            field=models.CharField(max_length=25, validators=[assets.models.no_spaces], verbose_name='Road Code'),
        ),
    ]
