# Generated by Django 2.2.4 on 2019-10-08 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("assets", "0017_create_surveys")]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="date_surveyed",
            field=models.DateField(blank=True, null=True, verbose_name="Date Surveyed"),
        )
    ]
