# Generated by Django 2.2.4 on 2019-10-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("assets", "0018_date_surveyed")]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="date_surveyed",
            field=models.DateTimeField(null=True, verbose_name="Date Surveyed"),
        )
    ]
