# Generated by Django 2.2.4 on 2019-10-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("assets", "0018_survey_changes")]

    operations = [
        migrations.AddField(
            model_name="road",
            name="number_lanes",
            field=models.IntegerField(
                blank=True,
                help_text="Enter the number of lanes of the road",
                null=True,
                verbose_name="Number of Lanes",
            ),
        )
    ]
