# Generated by Django 2.2.4 on 2019-11-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_rename_administrative_area_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='road_type',
            field=models.CharField(blank=True, choices=[('NAT', 'National'), ('HIGH', 'Highway'), ('MUN', 'Municipal'), ('URB', 'Urban'), ('RUR', 'Rural')], help_text='Choose the road class', max_length=4, null=True, verbose_name='Road Class'),
        ),
    ]
