# Generated by Django 2.2.4 on 2019-12-18 00:20

import assets.models
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0023_rainfall_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "road",
                    models.CharField(
                        max_length=25,
                        validators=[assets.models.no_spaces],
                        verbose_name="Road Code",
                    ),
                ),
                (
                    "primary_attribute",
                    models.CharField(max_length=50, verbose_name="Primary Attribute"),
                ),
                (
                    "max_date_surveyed",
                    models.DateTimeField(null=True, verbose_name="Date Surveyed"),
                ),
                (
                    "secondary_attribute",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttributeEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "road",
                    models.CharField(
                        max_length=25,
                        validators=[assets.models.no_spaces],
                        verbose_name="Road Code",
                    ),
                ),
                (
                    "survey_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Survey Id"
                    ),
                ),
                (
                    "chainage_start",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="Enter chainage for survey starting point",
                        max_digits=12,
                        null=True,
                        verbose_name="Start Chainage (Km)",
                    ),
                ),
                (
                    "chainage_end",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="Enter chainage for survey ending point",
                        max_digits=12,
                        null=True,
                        verbose_name="End Chainage (Km)",
                    ),
                ),
                ("values", django.contrib.postgres.fields.hstore.HStoreField()),
                (
                    "date_surveyed",
                    models.DateTimeField(null=True, verbose_name="Date Surveyed"),
                ),
                (
                    "user_id",
                    models.IntegerField(blank=True, null=True, verbose_name="User Id"),
                ),
                ("added_by", models.CharField(max_length=50, verbose_name="Added By")),
                (
                    "primary_attribute",
                    models.CharField(max_length=50, verbose_name="Primary Attribute"),
                ),
                (
                    "attribute_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attribute_entries",
                        to="assets.AttributeTable",
                        verbose_name="Attribute Table",
                    ),
                ),
            ],
        ),
    ]
