# Generated by Django 2.2.4 on 2020-01-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0025_auto_20200109_0028"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attributetable", name="unique_attribute_date",
        ),
        migrations.RenameField(
            model_name="attributeentry", old_name="road", new_name="road_code",
        ),
        migrations.RenameField(
            model_name="attributetable", old_name="road", new_name="road_code",
        ),
        migrations.RenameField(
            model_name="survey", old_name="road", new_name="road_code",
        ),
        migrations.AddField(
            model_name="attributeentry",
            name="road_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Road Id"),
        ),
        migrations.AddField(
            model_name="attributetable",
            name="road_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Road Id"),
        ),
        migrations.AddField(
            model_name="road",
            name="geom_end_chainage",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Do not edit",
                max_digits=12,
                null=True,
                verbose_name="Geometry End Chainage",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="geom_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Do not edit",
                max_digits=8,
                null=True,
                verbose_name="Geometry Length (m)",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="geom_start_chainage",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Do not edit",
                max_digits=12,
                null=True,
                verbose_name="Geometry Start Chainage",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="road_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Road Id"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="source",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Choose the source of the survey",
                max_length=155,
                null=True,
                verbose_name="Source",
            ),
        ),
        migrations.AddConstraint(
            model_name="attributetable",
            constraint=models.UniqueConstraint(
                fields=("road_id", "max_date_surveyed", "primary_attribute"),
                name="unique_attribute_date",
            ),
        ),
    ]
