# Generated by Django 2.2.4 on 2020-01-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0026_support_report_fixes"),
    ]

    operations = [
        migrations.DeleteModel(name="AttributeEntry",),
        migrations.DeleteModel(name="AttributeTable",),
    ]
