# Generated by Django 2.2.4 on 2020-01-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("csv_data_sources", "0001_initial"),
        ("assets", "0027_auto_20200114_0742"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoughnessSurvey",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("csv_data_sources.csvdata",),
        ),
    ]
