# Generated by Django 2.2.4 on 2020-02-25 02:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0028_roughnesssurvey"),
    ]

    operations = [
        # migrations.AddIndex(
        #     model_name="road",
        #     index=django.contrib.postgres.indexes.GistIndex(
        #         fields=["geom"], name="assets_road_geom_8ade04_gist"
        #     ),
        # ),
    ]
