# Generated by Django 2.2.4 on 2020-02-11 01:36

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0030_tweak_road_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="structure_id",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[assets.models.no_spaces],
                verbose_name="Structure Id",
            ),
        ),
    ]
