# Generated by Django 2.2.4 on 2020-02-21 10:26

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0031_survey_structure_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="asset_code",
            field=models.CharField(
                default="-1",
                max_length=25,
                validators=[assets.models.no_spaces],
                verbose_name="Asset Code",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survey",
            name="asset_id",
            field=models.CharField(
                default=self.structure_id,
                max_length=15,
                validators=[assets.models.no_spaces],
                verbose_name="Asset Id",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="survey",
            name="road_code",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[assets.models.no_spaces],
                verbose_name="Road Code",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="road_id",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[assets.models.no_spaces],
                verbose_name="Road Id",
            ),
        ),
        migrations.RemoveField(model_name="survey", name="structure_id",),
    ]
