# Generated by Django 2.2.4 on 2020-02-21 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0031_survey_structure_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bridge",
            name="span_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Enter span length",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="Span Length (m)",
            ),
        ),
    ]
