# Generated by Django 2.2.4 on 2020-02-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0032_fix_span_length_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="traffic_level",
            field=models.CharField(
                blank=True,
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                help_text="Choose the traffic volume for the road link",
                max_length=1,
                null=True,
                verbose_name="Traffic Data",
            ),
        ),
    ]
