# Generated by Django 2.2.4 on 2020-02-24 03:15

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0033_traffic_verbose_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survey", old_name="structure_id", new_name="asset_id",
        ),
        migrations.AlterField(
            model_name="survey",
            name="asset_id",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[assets.models.no_spaces],
                verbose_name="Asset Id",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="asset_code",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[assets.models.no_spaces],
                verbose_name="Asset Code",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="road_code",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[assets.models.no_spaces],
                verbose_name="Road Code",
            ),
        ),
    ]
