# Generated by Django 2.2.4 on 2020-02-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0034_carriageway_width_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="surface_condition",
            field=models.CharField(
                blank=True,
                choices=[("1", "Good"), ("2", "Fair"), ("3", "Poor"), ("4", "Bad")],
                help_text="Choose road link surface condition according to the Surface Distress Index (SDI): Good (SDI<=2), fair (2<SDI<=3), poor (3<SDI<=4) or bad (SDI>4)",
                max_length=1,
                null=True,
                verbose_name="Surface Condition (SDI)",
            ),
        ),
    ]
