# Generated by Django 2.2.4 on 2020-03-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0038_rename_asset_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="construction_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Road Construction Year"
            ),
        ),
    ]
