# Generated by Django 2.2.4 on 2020-03-10 03:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0039_road_construction_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bridge",
            name="geojson_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.CollatedGeoJsonFile",
            ),
        ),
        migrations.CreateModel(
            name="RoadFeatureAttributes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attributes",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Attributes"
                    ),
                ),
                (
                    "road",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.Road",
                        verbose_name="Road",
                    ),
                ),
            ],
        ),
    ]
