# Generated by Django 2.2.4 on 2020-03-06 03:18

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0040_roadfeatureattributes_20200310_0313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bridge",
            name="structure_code",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                unique=True,
                validators=[assets.models.no_spaces],
                verbose_name="Structure Code",
            ),
        ),
        migrations.AlterField(
            model_name="culvert",
            name="structure_code",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                unique=True,
                validators=[assets.models.no_spaces],
                verbose_name="Structure Code",
            ),
        ),
    ]
