# Generated by Django 2.2.4 on 2020-03-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0040_roadfeatureattributes_20200310_0313"),
    ]

    def insertData(apps, schema_editor):
        # These are present in the RRMPIS shapefile data - but they are free-form text, not codified
        FACILITY_TYPE_CHOICES = [
            ("1", "Health facility"),
            ("2", "School"),
            ("3", "Police/security station"),
            ("4", "Fire station"),
            ("5", "Recreational area"),
        ]
        # These are present in the RRMPIS shapefile data - but they are free-form text, not codified
        ECONOMIC_AREA_CHOICES = [
            ("1", "Fishing"),
            ("2", "Farming"),
            ("3", "Market"),
            ("4", "Tourism"),
            ("5", "Commercial"),
            ("6", "Industrial"),
            ("7", "Cash crops"),
        ]
        # These are present in the RRMPIS shapefile data - but they are free-form text, not codified
        CONNECTION_TYPE_CHOICES = [
            ("1", "Connects municipalities"),
            ("2", "Connects Dili to municipal centers"),
            ("3", "Connects administrative posts"),
            ("4", "Connects to land border"),
            ("5", "Connects to seaport"),
            ("6", "Connects to airport"),
        ]

        FacilityType = apps.get_model("assets", "FacilityType")
        for c in FACILITY_TYPE_CHOICES:
            record = FacilityType(code=c[0], name=c[1], name_en=c[1])
            record.save()

        EconomicArea = apps.get_model("assets", "EconomicArea")
        for c in ECONOMIC_AREA_CHOICES:
            record = EconomicArea(code=c[0], name=c[1], name_en=c[1])
            record.save()

        ConnectionType = apps.get_model("assets", "ConnectionType")
        for c in CONNECTION_TYPE_CHOICES:
            record = ConnectionType(code=c[0], name=c[1], name_en=c[1])
            record.save()

    operations = [
        migrations.CreateModel(
            name="ConnectionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "name_tet",
                    models.CharField(max_length=50, null=True, verbose_name="Name"),
                ),
                (
                    "name_pt",
                    models.CharField(max_length=50, null=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=50, null=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EconomicArea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "name_tet",
                    models.CharField(max_length=50, null=True, verbose_name="Name"),
                ),
                (
                    "name_pt",
                    models.CharField(max_length=50, null=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=50, null=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacilityType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "name_tet",
                    models.CharField(max_length=50, null=True, verbose_name="Name"),
                ),
                (
                    "name_pt",
                    models.CharField(max_length=50, null=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=50, null=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="road",
            name="served_connection_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Choose the types of connections facilitated by this road",
                related_name="roads",
                to="assets.ConnectionType",
                verbose_name="Types of Connections Served",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="served_economic_areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Choose economic areas served by this road",
                related_name="roads",
                to="assets.EconomicArea",
                verbose_name="Economic Areas Served",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="served_facilities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Choose facilities served by this road",
                related_name="roads",
                to="assets.FacilityType",
                verbose_name="Facilities Served",
            ),
        ),
        migrations.RunPython(insertData),
    ]
