# Generated by Django 2.2.4 on 2020-03-13 05:13

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0041_roughnesssurvey"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="survey",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["values"], name="assets_surv_values_c97cc5_gist"
            ),
        ),
    ]
