# Generated by Django 2.2.4 on 2020-03-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0042_road_fields_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="served_connection_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Choose the types of connections facilitated by this road",
                related_name="roads",
                to="assets.ConnectionType",
                verbose_name="Connections Served",
            ),
        ),
    ]
