# Generated by Django 2.2.4 on 2020-03-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0043_connection_types_verbose_name"),
        ("assets", "0042_surveys_gist_index"),
        ("assets", "0041_unique_structure_codes"),
    ]

    operations = []
