# Generated by Django 2.2.4 on 2020-03-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0045_photos'),
        ('assets', '0045_plans_and_snapshots'),
    ]

    operations = [
    ]
