# Generated by Django 2.2.4 on 2020-04-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0046_merge_20200331_0832"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bridge",
            name="chainage",
            field=models.IntegerField(
                blank=True,
                help_text="Enter chainage point for the structure",
                null=True,
                verbose_name="Chainage",
            ),
        ),
        migrations.AlterField(
            model_name="culvert",
            name="chainage",
            field=models.IntegerField(
                blank=True,
                help_text="Enter chainage point for the structure",
                null=True,
                verbose_name="Chainage",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="geom_end_chainage",
            field=models.IntegerField(
                blank=True,
                help_text="Do not edit",
                null=True,
                verbose_name="Geometry End Chainage",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="geom_length",
            field=models.IntegerField(
                blank=True,
                help_text="Do not edit",
                null=True,
                verbose_name="Geometry Length (m)",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="geom_start_chainage",
            field=models.IntegerField(
                blank=True,
                help_text="Do not edit",
                null=True,
                verbose_name="Geometry Start Chainage",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="link_end_chainage",
            field=models.IntegerField(
                blank=True,
                help_text="Enter chainage for link ending point",
                null=True,
                verbose_name="Link End Chainage",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="link_start_chainage",
            field=models.IntegerField(
                blank=True,
                help_text="Enter chainage for link starting point",
                null=True,
                verbose_name="Link Start Chainage",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="chainage_end",
            field=models.IntegerField(
                blank=True,
                help_text="Enter chainage for survey ending point",
                null=True,
                verbose_name="End Chainage (Km)",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="chainage_start",
            field=models.IntegerField(
                blank=True,
                help_text="Enter chainage for survey starting point",
                null=True,
                verbose_name="Start Chainage (Km)",
            ),
        ),
    ]
