# Generated by Django 2.2.4 on 2020-04-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0046_merge_20200331_0832"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="planning_period",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Planning Period"
            ),
        ),
    ]
