# Generated by Django 2.2.4 on 2020-04-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0047_plan_planning_period"),
        ("assets", "0047_chainage_int_20200402_0123"),
    ]

    operations = []
