# Generated by Django 2.2.4 on 2020-04-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0047_survey_report_tables"),
        ("assets", "0048_merge_20200402_0318"),
    ]

    operations = []
