# Generated by Django 2.2.4 on 2020-04-09 05:02

import assets.models
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0051_plansnapshot_last_modified"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriftClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="DriftMaterialType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="Drift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=32751
                    ),
                ),
                (
                    "road_id",
                    models.IntegerField(blank=True, null=True, verbose_name="Road Id"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="last modified"),
                ),
                (
                    "structure_code",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        unique=True,
                        validators=[assets.models.no_spaces],
                        verbose_name="Structure Code",
                    ),
                ),
                (
                    "structure_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NAT", "National"),
                            ("HIGH", "Highway"),
                            ("MUN", "Municipal"),
                            ("URB", "Urban"),
                            ("RUR", "Rural"),
                        ],
                        help_text="Choose the structure class",
                        max_length=4,
                        null=True,
                        verbose_name="Structure Class",
                    ),
                ),
                (
                    "administrative_area",
                    models.CharField(
                        default=None,
                        help_text="Choose the municipality for the structure",
                        max_length=50,
                        null=True,
                        verbose_name="Municipality",
                    ),
                ),
                (
                    "road_code",
                    models.CharField(
                        blank=True,
                        help_text="Enter the Road Code associated with the structure",
                        max_length=25,
                        null=True,
                        validators=[assets.models.no_spaces],
                        verbose_name="Road Code",
                    ),
                ),
                (
                    "construction_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Structure Construction Year",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Enter structure length",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Structure Length (m)",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Enter structure width",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Structure Width (m)",
                    ),
                ),
                (
                    "chainage",
                    models.IntegerField(
                        blank=True,
                        help_text="Enter chainage point for the structure",
                        null=True,
                        verbose_name="Chainage",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Enter structure height",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Structure Height (m)",
                    ),
                ),
                (
                    "number_cells",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Number of Cells",
                    ),
                ),
                (
                    "geojson_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="assets.CollatedGeoJsonFile",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the drift material",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.DriftMaterialType",
                        verbose_name="Material",
                    ),
                ),
                (
                    "protection_downstream",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the downstream protection type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drift_protection_downstream",
                        to="assets.StructureProtectionType",
                        verbose_name="Protection Downstream",
                    ),
                ),
                (
                    "protection_upstream",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the upstream protection type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drift_protection_upstream",
                        to="assets.StructureProtectionType",
                        verbose_name="Protection Upstream",
                    ),
                ),
                (
                    "structure_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the drift type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.DriftClass",
                        verbose_name="Drift Type",
                    ),
                ),
            ],
        ),
    ]
