# Generated by Django 2.2.4 on 2020-05-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0055_photos_to_medias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bridge",
            name="asset_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAT", "National"),
                    ("MUN", "Municipal"),
                    ("URB", "Urban"),
                    ("RUR", "Rural"),
                ],
                help_text="Choose the structure class",
                max_length=4,
                null=True,
                verbose_name="Structure Class",
            ),
        ),
        migrations.AlterField(
            model_name="culvert",
            name="asset_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAT", "National"),
                    ("MUN", "Municipal"),
                    ("URB", "Urban"),
                    ("RUR", "Rural"),
                ],
                help_text="Choose the structure class",
                max_length=4,
                null=True,
                verbose_name="Structure Class",
            ),
        ),
        migrations.AlterField(
            model_name="drift",
            name="asset_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAT", "National"),
                    ("MUN", "Municipal"),
                    ("URB", "Urban"),
                    ("RUR", "Rural"),
                ],
                help_text="Choose the structure class",
                max_length=4,
                null=True,
                verbose_name="Structure Class",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="asset_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAT", "National"),
                    ("MUN", "Municipal"),
                    ("URB", "Urban"),
                    ("RUR", "Rural"),
                ],
                help_text="Choose the asset class",
                max_length=4,
                null=True,
                verbose_name="Asset Class",
            ),
        ),
        migrations.AlterField(
            model_name="plansnapshot",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("NAT", "National"),
                    ("MUN", "Municipal"),
                    ("URB", "Urban"),
                    ("RUR", "Rural"),
                ],
                help_text="Choose the asset class",
                max_length=4,
                verbose_name="Asset Class",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="asset_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAT", "National"),
                    ("MUN", "Municipal"),
                    ("URB", "Urban"),
                    ("RUR", "Rural"),
                ],
                help_text="Choose the asset class",
                max_length=4,
                null=True,
                verbose_name="Asset Class",
            ),
        ),
    ]
