# Generated by Django 2.2.4 on 2020-06-26 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0056_highway_class_removal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="carriageway_width",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Enter the width of the link carriageway",
                max_digits=3,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Carriageway Width",
            ),
        ),
    ]
