# Generated by Django 2.2.4 on 2020-08-27 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0057_auto_20200626_0557"),
    ]

    operations = [
        migrations.AlterField(
            model_name="culvert",
            name="geojson_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.CollatedGeoJsonFile",
            ),
        ),
        migrations.AlterField(
            model_name="drift",
            name="geojson_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.CollatedGeoJsonFile",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="geojson_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.CollatedGeoJsonFile",
            ),
        ),
    ]
