# Generated by Django 2.2.4 on 2020-10-01 05:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0058_geojson_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriftFeatureAttributes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attributes",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Attributes"
                    ),
                ),
                (
                    "drift",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.Drift",
                        verbose_name="Drift",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CulvertFeatureAttributes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attributes",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Attributes"
                    ),
                ),
                (
                    "culvert",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.Culvert",
                        verbose_name="Culvert",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BridgeFeatureAttributes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attributes",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Attributes"
                    ),
                ),
                (
                    "bridge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.Bridge",
                        verbose_name="Bridge",
                    ),
                ),
            ],
        ),
    ]
